/**
 * Stable public API for @affino/datagrid-core.
 * Keep this surface semver-safe and intentionally narrow.
 */
export * from "./types/index.js"

export {
  createInMemoryDataGridSettingsAdapter,
  type DataGridColumnStateSnapshot,
  type DataGridSettingsAdapter,
  type DataGridGroupState,
  type DataGridPinPosition,
} from "./settings/dataGridSettingsAdapter.js"

export {
  DATAGRID_ADVANCED_ENTRYPOINTS,
  DATAGRID_DEPRECATION_WINDOWS,
  DATAGRID_EVENT_TIER_ENTRYPOINTS,
  DATAGRID_EVENT_TIERS,
  DATAGRID_FORBIDDEN_DEEP_IMPORT_PATTERNS,
  DATAGRID_INTERNAL_ENTRYPOINTS,
  DATAGRID_PUBLIC_PACKAGE_VERSION,
  DATAGRID_PUBLIC_PROTOCOL_VERSION,
  DATAGRID_SEMVER_RULES,
  DATAGRID_STABLE_ENTRYPOINTS,
  compareDatagridSemver,
  createDataGridEventEnvelope,
  getDataGridVersionedPublicProtocol,
  isDataGridEventTier,
  resolveDatagridDeprecationStatus,
  type DataGridDeprecationSnapshot,
  type DataGridDeprecationStatus,
  type DataGridDeprecationWindow,
  type DataGridEventAffectedRange,
  type DataGridEventEnvelope,
  type DataGridEventPhase,
  type DataGridEventSource,
  type DataGridEventTier,
  type DataGridSemver,
  type DataGridStableEventMap,
  type DataGridStableEventName,
  type DataGridVersionedPublicProtocol,
} from "./protocol/index.js"

export {
  createDataGridCore,
  type DataGridCoreEventService,
  type DataGridCoreRowModelService,
  type DataGridCoreColumnModelService,
  type DataGridCoreEditService,
  type DataGridCoreTransactionService,
  type DataGridCoreSelectionService,
  type DataGridCoreViewportService,
  type DataGridCoreServiceByName,
  type DataGridCore,
  type DataGridCoreLifecycleState,
  type DataGridCoreService,
  type DataGridCoreServiceContext,
  type DataGridCoreServiceName,
  type DataGridCoreServiceRegistry,
  type CreateDataGridCoreOptions,
} from "./core/gridCore.js"

export {
  createDataGridApi,
  type DataGridApi,
  type CreateDataGridApiFromCoreOptions,
  type CreateDataGridApiFromDepsOptions,
  type CreateDataGridApiDependencies,
  type CreateDataGridApiOptions,
  type DataGridCellRefreshEntry,
  type DataGridCellRefreshOptions,
  type DataGridCellRefreshRange,
  type DataGridCellsRefreshBatch,
  type DataGridCellsRefreshListener,
  type DataGridRefreshOptions,
  type DataGridApplyEditsOptions,
  type DataGridApiMutationControlOptions,
  type DataGridApiPivotNamespace,
  type DataGridApiRowSelectionNamespace,
  type DataGridApiSelectionNamespace,
  type DataGridApiTransactionNamespace,
  type DataGridApiRowsNamespace,
  type DataGridApiDataNamespace,
  type DataGridApiColumnsNamespace,
  type DataGridApiViewNamespace,
  type DataGridApiCapabilities,
  type DataGridApiComputeNamespace,
  type DataGridApiDiagnosticsNamespace,
  type DataGridApiDiagnosticsSnapshot,
  type DataGridApiFormulaExplainEntry,
  type DataGridApiFormulaExplainSnapshot,
  type DataGridApiRowModelDiagnostics,
  type DataGridApiLifecycleNamespace,
  type DataGridApiMetaNamespace,
  type DataGridApiSchemaSnapshot,
  type DataGridApiSchemaColumn,
  type DataGridApiRuntimeInfo,
  type DataGridApiPolicyNamespace,
  type DataGridApiProjectionMode,
  type DataGridApiPluginDefinition,
  type DataGridApiPluginsNamespace,
  type DataGridApiStateNamespace,
  type DataGridApiEventsNamespace,
  type DataGridApiEventMap,
  type DataGridApiEventName,
  type DataGridApiEventPayload,
  type DataGridApiErrorCode,
  type DataGridApiErrorEvent,
  type DataGridMigrateStateOptions,
  type DataGridSetStateOptions,
  type DataGridUnifiedRowsState,
  type DataGridUnifiedColumnState,
  type DataGridUnifiedState,
  type DataGridPivotLayoutColumnState,
  type DataGridPivotLayoutSnapshot,
  type DataGridPivotLayoutImportOptions,
  type DataGridPivotInteropSnapshot,
  type DataGridSelectionSummaryApiOptions,
} from "./core/gridApi.js"

export {
  type DataGridSelectionSnapshot,
  type DataGridSelectionSnapshotRange,
  type GridSelectionSnapshot,
  type GridSelectionSnapshotRange,
} from "./selection/snapshot.js"

export {
  clearDataGridRowFocus,
  clearDataGridSelectedRows,
  dataGridRowSelectionSnapshotsEqual,
  deselectDataGridRows,
  isDataGridRowSelected,
  normalizeDataGridRowSelectionSnapshot,
  reconcileDataGridRowSelectionSnapshot,
  replaceDataGridSelectedRows,
  selectDataGridRows,
  setDataGridRowFocused,
  setDataGridRowSelected,
  type DataGridRowSelectionSnapshot,
} from "./selection/rowSelection.js"

export {
  createDataGridSelectionSummary,
  type CreateDataGridSelectionSummaryOptions,
  type DataGridSelectionAggregationKind,
  type DataGridSelectionSummaryScope,
  type DataGridSelectionSummaryColumnConfig,
  type DataGridSelectionSummaryColumnSnapshot,
  type DataGridSelectionSummarySnapshot,
} from "./selection/selectionSummary.js"

export {
  analyzeDataGridSpreadsheetCellInput,
  createDataGridSpreadsheetFormulaEditorModel,
  createDataGridSpreadsheetSheetModel,
  createDataGridSpreadsheetWorkbookModel,
  formatDataGridSpreadsheetFormulaReference,
  insertDataGridSpreadsheetFormulaReference,
  rewriteDataGridSpreadsheetFormulaReferences,
  resolveDataGridSpreadsheetActiveFormulaReference,
  type AnalyzeDataGridSpreadsheetCellInputOptions,
  type CreateDataGridSpreadsheetSheetModelOptions,
  type CreateDataGridSpreadsheetWorkbookModelOptions,
  type DataGridSpreadsheetWorkbookDiagnostic,
  type DataGridSpreadsheetWorkbookDiagnosticCode,
  type DataGridSpreadsheetWorkbookDiagnosticSeverity,
  type CreateDataGridSpreadsheetFormulaEditorModelOptions,
  type DataGridSpreadsheetCellAddress,
  type DataGridSpreadsheetCellInputAnalysis,
  type DataGridSpreadsheetCellInputKind,
  type DataGridSpreadsheetCellInputPatch,
  type DataGridSpreadsheetCellSnapshot,
  type DataGridSpreadsheetCellStylePatch,
  type DataGridSpreadsheetColumnInput,
  type DataGridSpreadsheetColumnSnapshot,
  type DataGridSpreadsheetFormulaCellSnapshot,
  type DataGridSpreadsheetFormulaEditorListener,
  type DataGridSpreadsheetFormulaEditorModel,
  type DataGridSpreadsheetFormulaEditorSnapshot,
  type DataGridSpreadsheetFormulaTableBinding,
  type DataGridSpreadsheetFormulaTablePatch,
  type DataGridSpreadsheetFormatFormulaReferenceOptions,
  type DataGridSpreadsheetFormulaReferenceInput,
  type DataGridSpreadsheetFormulaReferenceOutputSyntax,
  type DataGridSpreadsheetFormulaReferenceSpan,
  type DataGridSpreadsheetInsertFormulaReferenceOptions,
  type DataGridSpreadsheetInsertFormulaReferenceResult,
  type DataGridSpreadsheetRowInput,
  type DataGridSpreadsheetRowSnapshot,
  type DataGridSpreadsheetSheetListener,
  type DataGridSpreadsheetSheetModel,
  type DataGridSpreadsheetSheetRowMutation,
  type DataGridSpreadsheetSheetRowMutationKind,
  type DataGridSpreadsheetSheetSnapshot,
  type DataGridSpreadsheetSheetState,
  type DataGridSpreadsheetSheetStateCell,
  type DataGridSpreadsheetSheetStateRow,
  type DataGridSpreadsheetViewAggregation,
  type DataGridSpreadsheetViewFilterClause,
  type DataGridSpreadsheetViewFilterStep,
  type DataGridSpreadsheetViewGroupByField,
  type DataGridSpreadsheetViewGroupStep,
  type DataGridSpreadsheetViewJoinColumn,
  type DataGridSpreadsheetViewJoinStep,
  type DataGridSpreadsheetViewPivotStep,
  type DataGridSpreadsheetViewProjectColumn,
  type DataGridSpreadsheetViewProjectStep,
  type DataGridSpreadsheetViewSortField,
  type DataGridSpreadsheetViewSortStep,
  type DataGridSpreadsheetViewStep,
  type DataGridSpreadsheetWorkbookDataSheetInput,
  type DataGridSpreadsheetWorkbookListener,
  type DataGridSpreadsheetWorkbookModel,
  type DataGridSpreadsheetWorkbookSheetHandle,
  type DataGridSpreadsheetWorkbookSheetKind,
  type DataGridSpreadsheetWorkbookSheetInput,
  type DataGridSpreadsheetWorkbookSheetSnapshot,
  type DataGridSpreadsheetWorkbookSheetStateExport,
  type DataGridSpreadsheetWorkbookState,
  type DataGridSpreadsheetWorkbookSnapshot,
  type DataGridSpreadsheetWorkbookSyncSnapshot,
  type DataGridSpreadsheetWorkbookViewDefinition,
  type DataGridSpreadsheetWorkbookViewSheetInput,
  type DataGridSpreadsheetWorkbookViewSheetModelOptions,
  type DataGridSpreadsheetStyle,
  type DataGridSpreadsheetTextSelection,
} from "./spreadsheet/index.js"

export {
  createClientRowComputeRuntime,
  DATAGRID_NOOP_CLIENT_PROJECTION_COMPUTE_STAGE_EXECUTOR,
  runDataGridClientProjectionComputeStageExecutor,
  createClientRowModel,
  createClientWorkbookModel,
  createDataSourceBackedRowModel,
  createServerBackedRowModel,
  createDataGridServerPivotRowId,
  type DataGridAdvancedFilter,
  type DataGridAdvancedFilterCondition,
  type DataGridAdvancedFilterConditionType,
  type DataGridAdvancedFilterExpression,
  type DataGridAdvancedFilterGroup,
  type DataGridAdvancedFilterNot,
  type DataGridColumnFilter,
  type DataGridColumnFilterSnapshotEntry,
  type DataGridColumnPredicateFilter,
  type DataGridColumnPredicateOperator,
  type DataGridColumnValueSetFilter,
  type DataGridColumnHistogram,
  type DataGridColumnHistogramEntry,
  type DataGridColumnHistogramOptions,
  type DataGridFilterClause,
  type DataGridFilterSnapshot,
  type DataGridSortAndFilterModelInput,
  type DataGridPaginationInput,
  type DataGridPaginationSnapshot,
  type DataGridGroupExpansionSnapshot,
  type DataGridGroupBySpec,
  type DataGridPivotSpec,
  type DataGridPivotValueSpec,
  type DataGridPivotColumn,
  type DataGridPivotColumnPathSegment,
  type DataGridPivotColumnSubtotalPosition,
  type DataGridPivotColumnGrandTotalPosition,
  type DataGridAggOp,
  type DataGridAggregationColumnSpec,
  type DataGridAggregationModel,
  type DataGridTreeDataMode,
  type DataGridTreeDataFilterMode,
  type DataGridTreeDataOrphanPolicy,
  type DataGridTreeDataCyclePolicy,
  type DataGridTreeDataBaseSpec,
  type DataGridTreeDataPathSpec,
  type DataGridTreeDataParentSpec,
  type DataGridTreeDataSpec,
  type DataGridTreeDataResolvedPathSpec,
  type DataGridTreeDataResolvedParentSpec,
  type DataGridTreeDataResolvedSpec,
  type DataGridTreeDataDiagnostics,
  type DataGridLegacyVisibleRow,
  type DataGridRowGroupMeta,
  type DataGridRowKind,
  type DataGridRowRenderMeta,
  type DataGridRowNode,
  type DataGridRowNodeInput,
  type DataGridRowNodeState,
  type DataGridRowPinState,
  type DataGridRowId,
  type DataGridRowIdResolver,
  type DataGridRowModel,
  type DataGridRowModelKind,
  type DataGridProjectionDiagnostics,
  type DataGridProjectionInvalidationReason,
  type DataGridProjectionMemoryDiagnostics,
  type DataGridProjectionPerformanceDiagnostics,
  type DataGridProjectionPipelineDiagnostics,
  type DataGridProjectionRowCounts,
  type DataGridProjectionStage,
  type DataGridProjectionStageTimes,
  type DataGridComputedDependencyToken,
  type DataGridFormulaRowSelector,
  type DataGridFormulaMetaField,
  type DataGridComputedFieldComputeContext,
  type DataGridComputedFieldDefinition,
  type DataGridComputedFieldSnapshot,
  type DataGridFormulaContextRecomputeRequest,
  type DataGridFormulaCyclePolicy,
  type DataGridFormulaFieldDefinition,
  type DataGridFormulaFieldSnapshot,
  type DataGridFormulaTableBinding,
  type DataGridFormulaTablePatch,
  type DataGridFormulaTableRowsSource,
  type DataGridFormulaTableSource,
  type DataGridFormulaFunctionDefinition,
  type DataGridFormulaFunctionRegistry,
  type DataGridFormulaArrayValue,
  type DataGridFormulaErrorValue,
  type DataGridFormulaIterativeCalculationOptions,
  type DataGridFormulaScalarValue,
  type DataGridFormulaValue,
  type DataGridFormulaRuntimeErrorCode,
  type DataGridFormulaRuntimeError,
  type DataGridFormulaDirtyCause,
  type DataGridFormulaDirtyRowCause,
  type DataGridProjectionFormulaDiagnostics,
  type DataGridFormulaComputeStageDiagnostics,
  type DataGridFormulaNodeComputeDiagnostics,
  type DataGridFormulaRowNodeRecomputeDiagnostics,
  type DataGridFormulaRowRecomputeDiagnosticsEntry,
  type DataGridFormulaRowRecomputeDiagnostics,
  type DataGridPivotCellDrilldownInput,
  type DataGridPivotCellDrilldown,
  type DataGridDataSource,
  type DataGridDataSourceBackpressureDiagnostics,
  type DataGridDataSourceInvalidation,
  type DataGridDataSourcePaginationPullContext,
  type DataGridDataSourcePullPriority,
  type DataGridDataSourcePivotPullContext,
  type DataGridDataSourcePullReason,
  type DataGridDataSourcePullRequest,
  type DataGridDataSourcePullResult,
  type DataGridDataSourceTreePullContext,
  type DataGridDataSourceTreePullOperation,
  type DataGridDataSourceTreePullScope,
  type DataGridDataSourcePushEvent,
  type DataGridDataSourcePushInvalidateEvent,
  type DataGridDataSourcePushListener,
  type DataGridDataSourcePushRemoveEvent,
  type DataGridDataSourcePushUpsertEvent,
  type DataGridDataSourceRowEntry,
  type DataGridServerPivotRowIdInput,
  type DataGridServerPivotRowRole,
  type DataGridRowModelSnapshot,
  type DataGridRowModelListener,
  type DataGridRowModelRefreshReason,
  type DataGridSortDirection,
  type DataGridSortState,
  type DataGridViewportRange,
  type ClientRowModel,
  type ClientWorkbookModel,
  type DataGridClientComputeDiagnostics,
  type DataGridClientComputeStagePlan,
  type DataGridClientComputeMode,
  type DataGridClientComputeExecutionPlanRequestOptions,
  type DataGridClientComputeRequest,
  type DataGridClientComputeTransport,
  type DataGridClientComputeTransportResult,
  type DataGridClientProjectionComputeStageExecutionContext,
  type DataGridClientProjectionComputeStageExecutionResult,
  type DataGridClientProjectionComputeStageExecutor,
  type DataGridClientRowPatch,
  type DataGridClientRowPatchOptions,
  type DataGridDependencyTokenDomain,
  type DataGridDependencyToken,
  type DataGridFieldNode,
  type DataGridComputedNode,
  type DataGridMetaNode,
  type DataGridDependencyNode,
  type DataGridDependencyEdgeKind,
  type DataGridDependencyEdge,
  type CreateDataGridDependencyEdgeInput,
  type DataGridFieldDependency,
  type DataGridDependencyKind,
  type DataGridDependencyCyclePolicy,
  type DataGridDependencyGraph,
  type DataGridRegisterDependencyOptions,
  type CreateDataGridDependencyGraphOptions,
  type DataGridClientPerformanceMode,
  type DataGridProjectionCacheStage,
  type DataGridProjectionCacheBucketPolicy,
  type DataGridProjectionModeCachePolicy,
  type DataGridProjectionCachePolicyMatrix,
  type DataGridResolvedProjectionCachePolicy,
  type DataGridProjectionPolicy,
  type CreateDataGridProjectionPolicyOptions,
  type CreateClientRowModelOptions,
  type CreateClientWorkbookModelOptions,
  type DataGridClientRowReorderInput,
  type DataGridWorkbookListener,
  type DataGridWorkbookSheetHandle,
  type DataGridWorkbookSheetInput,
  type DataGridWorkbookSheetSnapshot,
  type DataGridWorkbookSnapshot,
  type DataGridWorkbookSyncSnapshot,
  type ServerBackedRowModel,
  type CreateServerBackedRowModelOptions,
  type DataSourceBackedRowModel,
  type CreateDataSourceBackedRowModelOptions,
  isDataGridDependencyTokenDomain,
  DATAGRID_FORMULA_META_FIELDS,
  isDataGridFormulaMetaField,
  normalizeDataGridDependencyToken,
  parseDataGridDependencyNode,
  createDataGridDependencyEdge,
  createDataGridDependencyGraph,
  DATAGRID_PROJECTION_CACHE_POLICY_MATRIX,
  createDataGridProjectionPolicy,
  resolveDataGridProjectionCachePolicy,
  buildDataGridAdvancedFilterExpressionFromLegacyFilters,
  cloneDataGridFilterSnapshot,
  evaluateColumnPredicateFilter,
  evaluateDataGridAdvancedFilterExpression,
  normalizeDataGridAdvancedFilterExpression,
  serializeColumnValueToToken,
  normalizePaginationInput,
  normalizeTreeDataSpec,
  cloneTreeDataSpec,
  isSameTreeDataSpec,
  buildPaginationSnapshot,
  getDataGridRowRenderMeta,
} from "./models/index.js"

export {
  createServerRowModel,
  type ServerRowModel,
  type ServerRowModelOptions,
  type ServerRowModelFetchResult,
} from "./models/server/serverRowModel.js"

export {
  createDataGridColumnModel,
  buildDataGridCellRenderModel,
  createDataGridCellTypeRegistry,
  formatDataGridCellValue,
  parseDataGridCellDraftValue,
  resolveDataGridCellClickAction,
  resolveDataGridCellKeyboardAction,
  resolveDataGridCellType,
  type DataGridColumnCapabilities,
  type DataGridColumnConstraintValue,
  type DataGridColumnConstraints,
  type DataGridColumnDataType,
  type DataGridColumnDateTimeFormatOptions,
  type DataGridColumnDef,
  type DataGridColumnFormat,
  type DataGridColumnInitialState,
  type DataGridColumnInput,
  type DataGridColumnModel,
  type DataGridColumnModelSnapshot,
  type DataGridColumnModelListener,
  type DataGridColumnOption,
  type DataGridColumnNumberFormatOptions,
  type DataGridColumnSnapshot,
  type DataGridColumnPin,
  type DataGridColumnPresentation,
  type DataGridColumnState,
  type DataGridColumnValueAccessors,
  type CreateDataGridColumnModelOptions,
  type BuildDataGridCellRenderModelOptions,
  type CreateDataGridCellTypeRegistryOptions,
  type DataGridCellClickAction,
  type DataGridCellEditorMode,
  type DataGridCellKeyboardAction,
  type DataGridCellRenderModel,
  type DataGridCellTypeDefinition,
  type DataGridCellTypeId,
  type DataGridCellTypeOption,
  type DataGridCellTypeRegistry,
  createDataGridEditModel,
  type CreateDataGridEditModelOptions,
  type DataGridEditModel,
  type DataGridEditModelListener,
  type DataGridEditModelSnapshot,
  type DataGridEditPatch,
  toggleDataGridCellValue,
} from "./models/index.js"
