/**
 * Stable public API for @affino/datagrid-core.
 * Keep this surface semver-safe and intentionally narrow.
 */
export * from "./types/index.js"

export {
  createInMemoryDataGridSettingsAdapter,
  type DataGridColumnStateSnapshot,
  type DataGridSettingsAdapter,
  type DataGridGroupState,
  type DataGridPinPosition,
} from "./dataGridSettingsAdapter.js"

export {
  DATAGRID_ADVANCED_ENTRYPOINTS,
  DATAGRID_DEPRECATION_WINDOWS,
  DATAGRID_EVENT_TIER_ENTRYPOINTS,
  DATAGRID_EVENT_TIERS,
  DATAGRID_FORBIDDEN_DEEP_IMPORT_PATTERNS,
  DATAGRID_INTERNAL_ENTRYPOINTS,
  DATAGRID_PUBLIC_PACKAGE_VERSION,
  DATAGRID_PUBLIC_PROTOCOL_VERSION,
  DATAGRID_SEMVER_RULES,
  DATAGRID_STABLE_ENTRYPOINTS,
  compareDatagridSemver,
  createDataGridEventEnvelope,
  getDataGridVersionedPublicProtocol,
  isDataGridEventTier,
  resolveDatagridDeprecationStatus,
  type DataGridDeprecationSnapshot,
  type DataGridDeprecationStatus,
  type DataGridDeprecationWindow,
  type DataGridEventAffectedRange,
  type DataGridEventEnvelope,
  type DataGridEventPhase,
  type DataGridEventSource,
  type DataGridEventTier,
  type DataGridSemver,
  type DataGridStableEventMap,
  type DataGridStableEventName,
  type DataGridVersionedPublicProtocol,
} from "./protocol/index.js"

export {
  createDataGridCore,
  type DataGridCoreEventService,
  type DataGridCoreRowModelService,
  type DataGridCoreColumnModelService,
  type DataGridCoreEditService,
  type DataGridCoreTransactionService,
  type DataGridCoreSelectionService,
  type DataGridCoreViewportService,
  type DataGridCoreServiceByName,
  type DataGridCore,
  type DataGridCoreLifecycleState,
  type DataGridCoreService,
  type DataGridCoreServiceContext,
  type DataGridCoreServiceName,
  type DataGridCoreServiceRegistry,
  type CreateDataGridCoreOptions,
} from "./core/gridCore.js"

export {
  createDataGridApi,
  type DataGridApi,
  type CreateDataGridApiFromCoreOptions,
  type CreateDataGridApiFromDepsOptions,
  type CreateDataGridApiDependencies,
  type CreateDataGridApiOptions,
  type DataGridCellRefreshEntry,
  type DataGridCellRefreshOptions,
  type DataGridCellRefreshRange,
  type DataGridCellsRefreshBatch,
  type DataGridCellsRefreshListener,
  type DataGridRefreshOptions,
  type DataGridApplyEditsOptions,
  type DataGridSelectionSummaryApiOptions,
} from "./core/gridApi.js"

export {
  type DataGridSelectionSnapshot,
  type DataGridSelectionSnapshotRange,
  type GridSelectionSnapshot,
  type GridSelectionSnapshotRange,
} from "./selection/snapshot.js"

export {
  createDataGridSelectionSummary,
  type CreateDataGridSelectionSummaryOptions,
  type DataGridSelectionAggregationKind,
  type DataGridSelectionSummaryScope,
  type DataGridSelectionSummaryColumnConfig,
  type DataGridSelectionSummaryColumnSnapshot,
  type DataGridSelectionSummarySnapshot,
} from "./selection/selectionSummary.js"

export {
  createClientRowModel,
  createServerBackedRowModel,
  type DataGridAdvancedFilter,
  type DataGridAdvancedFilterCondition,
  type DataGridAdvancedFilterConditionType,
  type DataGridAdvancedFilterExpression,
  type DataGridAdvancedFilterGroup,
  type DataGridAdvancedFilterNot,
  type DataGridColumnFilter,
  type DataGridColumnFilterSnapshotEntry,
  type DataGridColumnPredicateFilter,
  type DataGridColumnPredicateOperator,
  type DataGridColumnValueSetFilter,
  type DataGridColumnHistogram,
  type DataGridColumnHistogramEntry,
  type DataGridColumnHistogramOptions,
  type DataGridFilterClause,
  type DataGridFilterSnapshot,
  type DataGridSortAndFilterModelInput,
  type DataGridPaginationInput,
  type DataGridPaginationSnapshot,
  type DataGridGroupExpansionSnapshot,
  type DataGridGroupBySpec,
  type DataGridAggOp,
  type DataGridAggregationColumnSpec,
  type DataGridAggregationModel,
  type DataGridTreeDataMode,
  type DataGridTreeDataFilterMode,
  type DataGridTreeDataOrphanPolicy,
  type DataGridTreeDataCyclePolicy,
  type DataGridTreeDataBaseSpec,
  type DataGridTreeDataPathSpec,
  type DataGridTreeDataParentSpec,
  type DataGridTreeDataSpec,
  type DataGridTreeDataResolvedPathSpec,
  type DataGridTreeDataResolvedParentSpec,
  type DataGridTreeDataResolvedSpec,
  type DataGridTreeDataDiagnostics,
  type DataGridLegacyVisibleRow,
  type DataGridRowGroupMeta,
  type DataGridRowKind,
  type DataGridRowRenderMeta,
  type DataGridRowNode,
  type DataGridRowNodeInput,
  type DataGridRowNodeState,
  type DataGridRowPinState,
  type DataGridRowId,
  type DataGridRowIdResolver,
  type DataGridRowModel,
  type DataGridRowModelKind,
  type DataGridProjectionDiagnostics,
  type DataGridProjectionStage,
  type DataGridRowModelSnapshot,
  type DataGridRowModelListener,
  type DataGridRowModelRefreshReason,
  type DataGridSortDirection,
  type DataGridSortState,
  type DataGridViewportRange,
  type ClientRowModel,
  type DataGridClientRowPatch,
  type DataGridClientRowPatchOptions,
  type DataGridDependencyTokenDomain,
  type DataGridDependencyToken,
  type DataGridFieldNode,
  type DataGridComputedNode,
  type DataGridMetaNode,
  type DataGridDependencyNode,
  type DataGridDependencyEdgeKind,
  type DataGridDependencyEdge,
  type CreateDataGridDependencyEdgeInput,
  type DataGridFieldDependency,
  type DataGridDependencyKind,
  type DataGridDependencyCyclePolicy,
  type DataGridDependencyGraph,
  type DataGridRegisterDependencyOptions,
  type CreateDataGridDependencyGraphOptions,
  type DataGridClientPerformanceMode,
  type DataGridProjectionCacheBucketPolicy,
  type DataGridProjectionModeCachePolicy,
  type DataGridProjectionCachePolicyMatrix,
  type DataGridResolvedProjectionCachePolicy,
  type DataGridProjectionPolicy,
  type CreateDataGridProjectionPolicyOptions,
  type CreateClientRowModelOptions,
  type DataGridClientRowReorderInput,
  type ServerBackedRowModel,
  type CreateServerBackedRowModelOptions,
  isDataGridDependencyTokenDomain,
  normalizeDataGridDependencyToken,
  parseDataGridDependencyNode,
  createDataGridDependencyEdge,
  createDataGridDependencyGraph,
  DATAGRID_PROJECTION_CACHE_POLICY_MATRIX,
  createDataGridProjectionPolicy,
  resolveDataGridProjectionCachePolicy,
  buildDataGridAdvancedFilterExpressionFromLegacyFilters,
  cloneDataGridFilterSnapshot,
  evaluateColumnPredicateFilter,
  evaluateDataGridAdvancedFilterExpression,
  normalizeDataGridAdvancedFilterExpression,
  serializeColumnValueToToken,
  normalizePaginationInput,
  normalizeTreeDataSpec,
  cloneTreeDataSpec,
  isSameTreeDataSpec,
  buildPaginationSnapshot,
  getDataGridRowRenderMeta,
} from "./models/index.js"

export {
  createDataGridColumnModel,
  type DataGridColumnDef,
  type DataGridColumnModel,
  type DataGridColumnModelSnapshot,
  type DataGridColumnModelListener,
  type DataGridColumnSnapshot,
  type DataGridColumnPin,
  type CreateDataGridColumnModelOptions,
  createDataGridEditModel,
  type CreateDataGridEditModelOptions,
  type DataGridEditModel,
  type DataGridEditModelListener,
  type DataGridEditModelSnapshot,
  type DataGridEditPatch,
} from "./models/index.js"
