export { default as DataGrid } from "./DataGrid.vue"
export { default as DataGridCell } from "./UiTableCell.vue"
export { default as DataGridColumnHeader } from "./UiTableColumnHeader.vue"
export { default as DataGridColumnVisibility } from "./UiTableColumnVisibility.vue"
export { default as DataGridHeader } from "./UiTableHeader.vue"
export { default as DataGridHeaderGroup } from "./UiTableHeaderGroup.vue"
export { default as DataGridModals } from "./UiTableModals.vue"
export { default as DataGridRowSurface } from "./UiTableRowSurface.vue"
export { default as DataGridRow } from "./UiTableRowSurface.vue"
export { default as DataGridStatusBar } from "./UiTableStatusBar.vue"
export { default as DataGridSummary } from "./UiTableSummary.vue"
export { default as DataGridToolbar } from "./UiTableToolbar.vue"
export { default as DataGridVirtualBodyRegion } from "./UiTableVirtualBodyRegion.vue"
export { default as DataGridViewport } from "./DataGridViewport.vue"
export { default as DataGridOverlayLayer } from "./DataGridOverlayLayer.vue"
export { default as DataGridZoomControl } from "./UiTableZoomControl.vue"

// Legacy compatibility shims:
// - deprecated: 2026-02-08
// - supported-until: 2026-08-31
// - removal-date: 2026-09-01
// New integration must use DataGrid* exports from this file.
export { default as UiTable } from "./UiTable.vue"
export { default as UiTableCell } from "./UiTableCell.vue"
export { default as UiTableColumnHeader } from "./UiTableColumnHeader.vue"
export { default as UiTableColumnVisibility } from "./UiTableColumnVisibility.vue"
export { default as UiTableHeader } from "./UiTableHeader.vue"
export { default as UiTableHeaderGroup } from "./UiTableHeaderGroup.vue"
export { default as UiTableModals } from "./UiTableModals.vue"
export { default as UiTableRowSurface } from "./UiTableRowSurface.vue"
export { default as UiTableRow } from "./UiTableRowSurface.vue"
export { default as UiTableStatusBar } from "./UiTableStatusBar.vue"
export { default as UiTableSummary } from "./UiTableSummary.vue"
export { default as UiTableToolbar } from "./UiTableToolbar.vue"
export { default as UiTableVirtualBodyRegion } from "./UiTableVirtualBodyRegion.vue"
export { default as UiTableViewport } from "./UiTableViewportSimple.vue"
export { default as UiTableOverlayLayer } from "./UiTableOverlayLayer.vue"
export { default as UiTableZoomControl } from "./UiTableZoomControl.vue"
export { default as UiVirtualDebugPanel } from "./UiVirtualDebugPanel.vue"
export { default as UiColumnHeader } from "./UiColumnHeader.vue"
export { default as UiModal } from "./UiModal.vue"
export { default as FilterPopover } from "./FilterPopover.vue"
export { default as AdvancedFilterModal } from "./AdvancedFilterModal.vue"
