import { palette, toRgb, toRgba, transparent } from "./palette"
import type { DataGridThemeTokens } from "./types"

export const defaultThemeTokens: DataGridThemeTokens = {
  gridFontFamily: '"Space Grotesk", "DM Sans", system-ui, sans-serif',
  gridFontSize: "0.78rem",
  gridTextColor: toRgba(palette.textPrimary, 0.55),
  gridBackgroundColor: toRgba(palette.midnight900, 0.95),
  gridTextPrimary: toRgb(palette.textPrimary),
  gridTextMuted: toRgba(palette.textPrimary, 0.7),
  gridTextSoft: toRgba(palette.textPrimary, 0.55),
  gridGlassBorder: toRgba(palette.white, 0.08),
  gridAccentStrong: toRgb(palette.sky500),
  headerBackgroundColor: toRgba(palette.midnight840, 0.98),
  headerTextColor: toRgb(palette.textPrimary),
  headerBorderColor: toRgba(palette.steel200, 0.22),
  headerPaddingX: "0.65rem",
  headerPaddingY: "0rem",
  headerHighlightBorderColor: toRgba(palette.sky300, 0.8),
  headerHighlightTextColor: toRgba(palette.sky200, 0.98),
  headerSelectedTextColor: toRgb(palette.textPrimary),
  headerSystemTextColor: toRgb(palette.textPrimary),
  bodyRowBackgroundColor: toRgba(palette.midnight875, 0.92),
  bodyRowTextColor: toRgba(palette.textPrimary, 0.55),
  bodyRowHoverBackgroundColor: toRgba(palette.midnight830, 0.88),
  bodyRowSelectedBackgroundColor: toRgba(palette.midnight800, 0.68),
  bodyRowSelectedTextColor: toRgb(palette.textPrimary),
  bodyCellPaddingX: "0.65rem",
  bodyCellPaddingY: "0rem",
  bodyCellBorderColor: toRgba(palette.steel200, 0.12),
  selectionCellBackgroundColor: toRgba(palette.sky500, 0.14),
  selectionCellTextColor: toRgb(palette.sky200),
  indexCellBackgroundColor: toRgba(palette.midnight850, 0.98),
  indexCellTextColor: toRgba(palette.textPrimary, 0.7),
  rowDividerSize: "1px",
  rowDividerColor: toRgba(palette.steel200, 0.14),
  columnDividerSize: "1px",
  columnDividerColor: toRgba(palette.steel200, 0.12),
  headerDividerSize: "1px",
  headerDividerColor: toRgba(palette.steel200, 0.22),
  summaryDividerSize: "1px",
  summaryDividerColor: toRgba(palette.steel200, 0.12),
  groupRowBackgroundColor: toRgba(palette.midnight875, 0.92),
  groupRowTextColor: toRgba(palette.sky300, 0.95),
  summaryRowBackgroundColor: toRgba(palette.midnight875, 0.92),
  summaryRowTextColor: toRgba(palette.textPrimary, 0.55),
  summaryLabelTextColor: toRgba(palette.textPrimary, 0.7),
  pinnedBackgroundColor: toRgba(palette.midnight850, 0.98),
  pinnedLeftBackgroundColor: toRgba(palette.midnight850, 0.98),
  pinnedRightBackgroundColor: toRgba(palette.midnight850, 0.98),
  pinnedShadow: `0 0 0 0 ${transparent()}`,
  pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.steel200, 0.2)}`,
  pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.steel200, 0.2)}`,
  pinnedLeftBorderColor: toRgba(palette.steel200, 0.2),
  pinnedLeftBorderWidth: "1px",
  pinnedRightBorderColor: toRgba(palette.steel200, 0.2),
  pinnedRightBorderWidth: "1px",
  gridHeroBackgroundStart: toRgba("#0b121d", 0.94),
  gridHeroBackgroundEnd: toRgba("#14223a", 0.92),
  gridChipBackground: toRgba(palette.white, 0.04),
  gridControlsBackground: toRgba("#090c14", 0.84),
  gridControlsInputBackground: toRgba(palette.white, 0.06),
  gridControlsSurfaceBackground: toRgba("#080d18", 0.98),
  gridFilterPanelBorderColor: toRgba(palette.sky300, 0.35),
  gridFilterPanelBackground: toRgba("#080e18", 0.94),
  gridFilterIndicatorActiveColor: toRgba(palette.sky300, 0.95),
  gridMetricsCardBackground: toRgba("#070a13", 0.86),
  gridViewportBackground: toRgba("#050810", 0.95),
  gridFocusOutlineColor: toRgba(palette.sky500, 0.8),
  gridHeaderRowBackgroundColor: toRgba("#060a14", 0.98),
  gridHeaderCellBackgroundColor: toRgba("#0b111f", 0.98),
  gridHeaderCellHoverBackgroundColor: toRgba("#121c2f", 0.99),
  gridHeaderFilterOpenBackgroundColor: toRgba("#132036", 0.99),
  gridGroupRowBorderColor: toRgba(palette.sky300, 0.45),
  gridRowSelectedStickyBackgroundColor: toRgba(palette.midnight780, 0.9),
  gridRowSelectedRangeBackgroundColor: toRgba(palette.sky500, 0.22),
  gridCheckboxAccentColor: toRgb(palette.sky500),
  gridSortIndicatorColor: toRgba(palette.sky300, 0.95),
  gridSortPriorityBorderColor: toRgba(palette.sky300, 0.45),
  gridHeaderFilterHighlightColor: toRgba(palette.sky300, 0.8),
  gridFilterTriggerBorderColor: toRgba(palette.steel200, 0.45),
  gridFilterTriggerBackgroundColor: toRgba(palette.midnight860, 0.92),
  gridFilterTriggerHoverBorderColor: toRgba(palette.sky300, 0.8),
  gridFilterTriggerHoverTextColor: toRgba(palette.sky200, 0.98),
  gridFilterTriggerActiveBorderColor: toRgba(palette.sky300, 0.85),
  gridFilterTriggerActiveBackgroundColor: toRgba("#082f49", 0.9),
  gridFilterTriggerActiveTextColor: toRgba(palette.sky200, 1),
  gridResizeHandleHoverColor: toRgba(palette.sky300, 0.9),
  gridNumericTextColor: toRgb(palette.sky200),
  gridEditableHoverBackgroundColor: toRgba("#101e34", 0.88),
  gridSelectionRangeBackgroundColor: toRgba(palette.sky500, 0.14),
  gridSelectionCopiedBorderColor: toRgba(palette.blue300, 0.85),
  gridSelectionCopiedBackgroundColor: toRgba(palette.sky500, 0.1),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.sky300, 0.14),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.indigo300, 0.14),
  gridSelectionAnchorBackgroundColor: toRgba(palette.sky500, 0.2),
  gridSelectionActiveBorderColor: toRgba(palette.sky200, 0.95),
  gridEditorBorderColor: toRgba(palette.steel200, 0.35),
  gridEditorBackgroundColor: toRgba("#090e19", 0.96),
  gridEditorFocusBorderColor: toRgba(palette.sky300, 0.75),
  gridEditorFocusRingColor: toRgba(palette.sky500, 0.25),
  gridEnumTriggerBorderColor: toRgba(palette.steel200, 0.45),
  gridEnumTriggerBackgroundColor: toRgba("#0b121e", 0.95),
  gridEnumTriggerTextColor: toRgba(palette.sky200, 0.95),
  gridEnumTriggerHoverBorderColor: toRgba(palette.sky300, 0.8),
  gridEnumTriggerHoverBackgroundColor: toRgba("#111f35", 0.98),
  gridStickyBackgroundColor: toRgba(palette.midnight850, 0.98),
  gridStickyShadowColor: toRgba(palette.steel200, 0.2),
  gridStickyRangeBackgroundColor: toRgba(palette.sky500, 0.24),
  gridStickyRangeBorderColor: toRgba(palette.sky300, 0.55),
  gridStickyAnchorBackgroundColor: toRgba(palette.sky500, 0.32),
  gridStickyAnchorBorderColor: toRgba(palette.sky200, 0.9),
  gridStickyActiveBorderColor: toRgba(palette.sky200, 1),
  gridHeaderStickyBackgroundColor: toRgba(palette.midnight840, 0.99),
  gridGroupStartGradientStart: toRgba(palette.sky500, 0.12),
  gridGroupStartGradientEnd: toRgba(palette.midnight875, 0.92),
  gridGroupBadgeTextColor: toRgba(palette.sky300, 0.95),
  gridSelectionOverlayBorderColor: toRgba(palette.sky500, 0.92),
  gridSelectionOverlayBackgroundColor: toRgba(palette.sky500, 0.08),
  gridSelectionOverlayFillBorderColor: toRgba(palette.sky300, 0.9),
  gridSelectionOverlayFillBackgroundColor: toRgba(palette.sky500, 0.05),
  gridSelectionOverlayMoveBorderColor: toRgba(palette.indigo300, 0.95),
  gridSelectionOverlayMoveBackgroundColor: toRgba(palette.indigo500, 0.07),
  gridSelectionHandleBorderColor: toRgba(palette.sky300, 0.95),
  gridSelectionHandleBackgroundColor: toRgba("#082f49", 0.95),
  gridMoveHandleHoverBackgroundColor: toRgba(palette.sky300, 0.2),
  gridHintBorderColor: toRgba(palette.steel200, 0.12),
  gridHintBackgroundColor: toRgba(palette.midnight875, 0.86),
  gridCopyMenuBorderColor: toRgba(palette.sky300, 0.35),
  gridCopyMenuBackgroundColor: toRgba("#090e1a", 0.97),
  gridCopyMenuShadowColor: toRgba("#030712", 0.58),
  gridCopyMenuItemHoverBorderColor: toRgba(palette.sky300, 0.4),
  gridCopyMenuItemHoverBackgroundColor: toRgba(palette.midnight830, 0.96),
}
