// src/datagrid/theme/tokens.ts
// Defines the mapping between logical tokens and CSS custom properties.

import type { DataGridThemeTokens } from "./types"

export const THEME_TOKEN_VARIABLE_MAP: Record<keyof DataGridThemeTokens, string> = {
  tableFontFamily: "--datagrid-font-family",
  tableFontSize: "--datagrid-font-size",
  tableTextColor: "--datagrid-text-color",
  tableBackgroundColor: "--datagrid-background-color",
  headerBackgroundColor: "--datagrid-header-background-color",
  headerTextColor: "--datagrid-header-text-color",
  headerBorderColor: "--datagrid-header-border-color",
  headerPaddingX: "--datagrid-header-padding-x",
  headerPaddingY: "--datagrid-header-padding-y",
  headerHighlightBorderColor: "--datagrid-header-highlight-border-color",
  headerHighlightTextColor: "--datagrid-header-highlight-text-color",
  headerSelectedTextColor: "--datagrid-header-selected-text-color",
  headerSystemTextColor: "--datagrid-header-system-text-color",
  bodyRowBackgroundColor: "--datagrid-row-background-color",
  bodyRowTextColor: "--datagrid-row-text-color",
  bodyRowHoverBackgroundColor: "--datagrid-row-hover-background-color",
  bodyRowSelectedBackgroundColor: "--datagrid-row-selected-background-color",
  bodyRowSelectedTextColor: "--datagrid-row-selected-text-color",
  bodyCellPaddingX: "--datagrid-body-cell-padding-x",
  bodyCellPaddingY: "--datagrid-body-cell-padding-y",
  bodyCellBorderColor: "--datagrid-cell-border-color",
  selectionCellBackgroundColor: "--datagrid-selection-cell-background-color",
  selectionCellTextColor: "--datagrid-selection-cell-text-color",
  indexCellBackgroundColor: "--datagrid-index-cell-background-color",
  indexCellTextColor: "--datagrid-index-cell-text-color",
  rowDividerSize: "--datagrid-row-divider-size",
  rowDividerColor: "--datagrid-row-divider-color",
  columnDividerSize: "--datagrid-column-divider-size",
  columnDividerColor: "--datagrid-column-divider-color",
  headerDividerSize: "--datagrid-header-divider-size",
  headerDividerColor: "--datagrid-header-divider-color",
  summaryDividerSize: "--datagrid-summary-divider-size",
  summaryDividerColor: "--datagrid-summary-divider-color",
  groupRowBackgroundColor: "--datagrid-group-row-background-color",
  groupRowTextColor: "--datagrid-group-row-text-color",
  summaryRowBackgroundColor: "--datagrid-summary-row-background-color",
  summaryRowTextColor: "--datagrid-summary-row-text-color",
  summaryLabelTextColor: "--datagrid-summary-label-text-color",
  pinnedBackgroundColor: "--datagrid-pinned-bg",
  pinnedLeftBackgroundColor: "--datagrid-pinned-left-bg",
  pinnedRightBackgroundColor: "--datagrid-pinned-right-bg",
  pinnedShadow: "--datagrid-pinned-shadow",
  pinnedLeftShadow: "--datagrid-pinned-left-shadow",
  pinnedRightShadow: "--datagrid-pinned-right-shadow",
  pinnedLeftBorderColor: "--datagrid-pinned-left-border-color",
  pinnedLeftBorderWidth: "--datagrid-pinned-left-border-width",
  pinnedRightBorderColor: "--datagrid-pinned-right-border-color",
  pinnedRightBorderWidth: "--datagrid-pinned-right-border-width",
}
