from __future__ import annotations

from typing import Any, Protocol


class GridDataAdapter(Protocol):
    async def health(self) -> None: ...

    async def pull(self, request: Any) -> Any: ...

    async def histogram(self, column_id: str, filter_model: dict[str, Any] | None) -> Any: ...

    async def commit_edits(self, request: Any) -> Any: ...

    async def resolve_fill_boundary(self, request: Any) -> Any: ...

    async def commit_fill(self, request: Any) -> Any: ...

    async def undo_operation(self, operation_id: str) -> Any: ...

    async def redo_operation(self, operation_id: str) -> Any: ...
