import type { DataGridThemeProp } from "@affino/datagrid-vue-app"

export const sheetsAppLightGridTheme: DataGridThemeProp = {
  tokens: {
    gridFontFamily: "var(--sheets-app-font-sans)",
    gridFontSize: "13px",
    gridTextColor: "var(--sheets-app-text-body)",
    gridBackgroundColor: "var(--sheets-app-surface)",
    gridTextPrimary: "var(--sheets-app-text-strong)",
    gridTextMuted: "var(--sheets-app-text-muted)",
    gridTextSoft: "var(--sheets-app-text-soft)",
    gridGlassBorder: "var(--sheets-app-border)",
    gridAccentStrong: "var(--sheets-app-accent)",
    headerBackgroundColor: "var(--sheets-app-surface-muted)",
    headerTextColor: "#31443a",
    headerBorderColor: "var(--sheets-app-border)",
    headerHighlightBorderColor: "var(--sheets-app-accent)",
    headerHighlightTextColor: "var(--sheets-app-accent)",
    headerSelectedTextColor: "var(--sheets-app-accent)",
    headerSystemTextColor: "#708074",
    bodyRowBackgroundColor: "var(--sheets-app-surface)",
    bodyRowTextColor: "var(--sheets-app-text-body)",
    bodyRowHoverBackgroundColor: "#f7faf8",
    bodyRowSelectedBackgroundColor: "var(--sheets-app-accent-soft)",
    bodyRowSelectedTextColor: "var(--sheets-app-text-strong)",
    bodyCellPaddingX: "12px",
    bodyCellPaddingY: "10px",
    bodyCellBorderColor: "#e3e8e4",
    selectionCellBackgroundColor: "var(--sheets-app-accent-soft)",
    selectionCellTextColor: "var(--sheets-app-text-strong)",
    indexCellBackgroundColor: "var(--sheets-app-surface-subtle)",
    indexCellTextColor: "var(--sheets-app-text-soft)",
    rowDividerSize: "1px",
    rowDividerColor: "#e3e8e4",
    columnDividerSize: "1px",
    columnDividerColor: "#edf0ee",
    headerDividerSize: "1px",
    headerDividerColor: "var(--sheets-app-border)",
    pinnedBackgroundColor: "var(--sheets-app-surface)",
    pinnedLeftBackgroundColor: "var(--sheets-app-surface)",
    pinnedRightBackgroundColor: "var(--sheets-app-surface)",
    gridViewportBackground: "var(--sheets-app-surface)",
    gridFocusOutlineColor: "var(--sheets-app-accent)",
    gridHeaderRowBackgroundColor: "var(--sheets-app-surface-muted)",
    gridHeaderCellBackgroundColor: "var(--sheets-app-surface-muted)",
    gridHeaderCellHoverBackgroundColor: "#edf4ef",
    gridHeaderFilterOpenBackgroundColor: "var(--sheets-app-accent-soft)",
    gridRowSelectedStickyBackgroundColor: "var(--sheets-app-accent-soft)",
    gridRowSelectedRangeBackgroundColor: "rgb(31 143 82 / 0.08)",
    gridCheckboxAccentColor: "var(--sheets-app-accent)",
    gridSortIndicatorColor: "var(--sheets-app-accent)",
    gridHeaderFilterHighlightColor: "var(--sheets-app-accent)",
    gridFilterTriggerBorderColor: "var(--sheets-app-border)",
    gridFilterTriggerBackgroundColor: "var(--sheets-app-surface)",
    gridFilterTriggerHoverBorderColor: "var(--sheets-app-accent)",
    gridFilterTriggerHoverTextColor: "var(--sheets-app-accent)",
    gridFilterTriggerActiveBorderColor: "var(--sheets-app-accent)",
    gridFilterTriggerActiveBackgroundColor: "var(--sheets-app-accent-soft)",
    gridFilterTriggerActiveTextColor: "var(--sheets-app-accent)",
    gridResizeHandleHoverColor: "var(--sheets-app-accent)",
    gridNumericTextColor: "var(--sheets-app-text-body)",
    gridEditableHoverBackgroundColor: "#f7faf8",
    gridSelectionRangeBackgroundColor: "rgb(31 143 82 / 0.06)",
    gridSelectionCopiedBorderColor: "var(--sheets-app-accent)",
    gridSelectionCopiedBackgroundColor: "rgb(31 143 82 / 0.08)",
    gridSelectionFillPreviewBackgroundColor: "rgb(31 143 82 / 0.12)",
    gridSelectionMovePreviewBackgroundColor: "rgb(34 49 38 / 0.08)",
    gridSelectionAnchorBackgroundColor: "var(--sheets-app-accent)",
    gridSelectionActiveBorderColor: "var(--sheets-app-accent)",
    gridEditorBorderColor: "var(--sheets-app-accent)",
    gridEditorBackgroundColor: "var(--sheets-app-surface)",
    gridEditorFocusBorderColor: "var(--sheets-app-accent)",
    gridEditorFocusRingColor: "rgb(31 143 82 / 0.16)",
    gridStickyBackgroundColor: "var(--sheets-app-surface)",
    gridStickyShadowColor: "rgb(21 34 25 / 0.08)",
    gridStickyRangeBackgroundColor: "rgb(31 143 82 / 0.08)",
    gridStickyRangeBorderColor: "var(--sheets-app-accent)",
    gridStickyAnchorBackgroundColor: "var(--sheets-app-accent)",
    gridStickyAnchorBorderColor: "var(--sheets-app-accent)",
    gridStickyActiveBorderColor: "var(--sheets-app-accent)",
    gridHeaderStickyBackgroundColor: "var(--sheets-app-surface-muted)",
    gridSelectionOverlayBorderColor: "var(--sheets-app-accent)",
    gridSelectionOverlayBackgroundColor: "rgb(31 143 82 / 0.05)",
    gridSelectionOverlayFillBorderColor: "var(--sheets-app-accent)",
    gridSelectionOverlayFillBackgroundColor: "rgb(31 143 82 / 0.1)",
    gridSelectionOverlayMoveBorderColor: "var(--sheets-app-text-body)",
    gridSelectionOverlayMoveBackgroundColor: "rgb(34 49 38 / 0.08)",
    gridSelectionHandleBorderColor: "var(--sheets-app-accent-contrast)",
    gridSelectionHandleBackgroundColor: "var(--sheets-app-accent)",
    gridMoveHandleHoverBackgroundColor: "var(--sheets-app-accent)",
    gridHintBorderColor: "var(--sheets-app-border)",
    gridHintBackgroundColor: "#f7faf8",
    gridColumnMenuBorderColor: "var(--sheets-app-border)",
    gridColumnMenuBackgroundColor: "var(--sheets-app-surface)",
    gridColumnMenuShadowColor: "rgb(21 34 25 / 0.12)",
    gridColumnMenuItemHoverBackgroundColor: "var(--sheets-app-surface-muted)",
    gridColumnMenuMutedTextColor: "#708074",
    gridColumnMenuFocusRingColor: "rgb(31 143 82 / 0.16)",
    gridColumnMenuSearchBorderColor: "var(--sheets-app-border)",
    gridColumnMenuSearchBackgroundColor: "#f8faf9",
  },
}
