import type { DataGridThemeProp } from "@affino/datagrid-vue-app"

export const sheetsAppLightGridTheme: DataGridThemeProp = {
  tokens: {
    gridFontFamily: "var(--sheets-app-font-sans)",
    gridFontSize: "13px",
    gridTextColor: "var(--sheets-app-text-body)",
    gridBackgroundColor: "var(--sheets-app-surface)",
    gridTextPrimary: "var(--sheets-app-text-strong)",
    gridTextMuted: "var(--sheets-app-text-muted)",
    gridTextSoft: "var(--sheets-app-text-soft)",
    gridGlassBorder: "var(--sheets-app-border)",
    gridAccentStrong: "var(--sheets-app-accent)",
    headerBackgroundColor: "var(--sheets-app-surface-muted)",
    headerTextColor: "#31443a",
    headerBorderColor: "var(--sheets-app-border)",
    headerPaddingX: "12px",
    headerPaddingY: "8px",
    headerHighlightBorderColor: "var(--sheets-app-accent)",
    headerHighlightTextColor: "var(--sheets-app-accent)",
    headerSelectedTextColor: "var(--sheets-app-accent)",
    headerSystemTextColor: "#708074",
    bodyRowBackgroundColor: "var(--sheets-app-surface)",
    bodyRowTextColor: "var(--sheets-app-text-body)",
    bodyRowHoverBackgroundColor: "#f7faf8",
    bodyRowSelectedBackgroundColor: "var(--sheets-app-accent-soft)",
    bodyRowSelectedTextColor: "var(--sheets-app-text-strong)",
    bodyCellPaddingX: "12px",
    bodyCellPaddingY: "10px",
    bodyCellBorderColor: "#e3e8e4",
    selectionCellBackgroundColor: "var(--sheets-app-accent-soft)",
    selectionCellTextColor: "var(--sheets-app-text-strong)",
    indexCellBackgroundColor: "var(--sheets-app-surface-subtle)",
    indexCellTextColor: "var(--sheets-app-text-soft)",
    rowDividerSize: "1px",
    rowDividerColor: "#e3e8e4",
    columnDividerSize: "1px",
    columnDividerColor: "#edf0ee",
    headerDividerSize: "1px",
    headerDividerColor: "var(--sheets-app-border)",
    summaryDividerSize: "1px",
    summaryDividerColor: "#e3e8e4",
    groupRowBackgroundColor: "var(--sheets-app-surface-subtle)",
    groupRowTextColor: "var(--sheets-app-text-body)",
    summaryRowBackgroundColor: "var(--sheets-app-surface-muted)",
    summaryRowTextColor: "var(--sheets-app-text-body)",
    summaryLabelTextColor: "var(--sheets-app-text-muted)",
    pinnedBackgroundColor: "var(--sheets-app-surface)",
    pinnedLeftBackgroundColor: "var(--sheets-app-surface)",
    pinnedRightBackgroundColor: "var(--sheets-app-surface)",
    pinnedShadow: "0 0 0 0 rgb(0 0 0 / 0)",
    pinnedLeftShadow: "inset -1px 0 0 var(--sheets-app-border)",
    pinnedRightShadow: "inset 1px 0 0 var(--sheets-app-border)",
    pinnedLeftBorderColor: "var(--sheets-app-border)",
    pinnedLeftBorderWidth: "1px",
    pinnedRightBorderColor: "var(--sheets-app-border)",
    pinnedRightBorderWidth: "1px",
    gridHeroBackgroundStart: "var(--sheets-app-surface)",
    gridHeroBackgroundEnd: "var(--sheets-app-surface-muted)",
    gridChipBackground: "var(--sheets-app-surface-subtle)",
    gridControlsBackground: "var(--sheets-app-surface-muted)",
    gridControlsInputBackground: "var(--sheets-app-surface)",
    gridControlsSurfaceBackground: "var(--sheets-app-surface)",
    gridFilterPanelBorderColor: "var(--sheets-app-border)",
    gridFilterPanelBackground: "var(--sheets-app-surface)",
    gridFilterIndicatorActiveColor: "var(--sheets-app-accent)",
    gridMetricsCardBackground: "var(--sheets-app-surface-muted)",
    gridViewportBackground: "var(--sheets-app-surface)",
    gridFocusOutlineColor: "var(--sheets-app-accent)",
    gridHeaderRowBackgroundColor: "var(--sheets-app-surface-muted)",
    gridHeaderCellBackgroundColor: "var(--sheets-app-surface-muted)",
    gridHeaderCellHoverBackgroundColor: "#edf4ef",
    gridHeaderFilterOpenBackgroundColor: "var(--sheets-app-accent-soft)",
    gridRowSelectedStickyBackgroundColor: "var(--sheets-app-accent-soft)",
    gridRowSelectedRangeBackgroundColor: "rgb(31 143 82 / 0.08)",
    gridCheckboxAccentColor: "var(--sheets-app-accent)",
    gridSortIndicatorColor: "var(--sheets-app-accent)",
    gridHeaderFilterHighlightColor: "var(--sheets-app-accent)",
    gridGroupRowBorderColor: "var(--sheets-app-border)",
    gridSortPriorityBorderColor: "var(--sheets-app-border)",
    gridFilterTriggerBorderColor: "var(--sheets-app-border)",
    gridFilterTriggerBackgroundColor: "var(--sheets-app-surface)",
    gridFilterTriggerHoverBorderColor: "var(--sheets-app-accent)",
    gridFilterTriggerHoverTextColor: "var(--sheets-app-accent)",
    gridFilterTriggerActiveBorderColor: "var(--sheets-app-accent)",
    gridFilterTriggerActiveBackgroundColor: "var(--sheets-app-accent-soft)",
    gridFilterTriggerActiveTextColor: "var(--sheets-app-accent)",
    gridResizeHandleHoverColor: "var(--sheets-app-accent)",
    gridNumericTextColor: "var(--sheets-app-text-body)",
    gridEditableHoverBackgroundColor: "#f7faf8",
    gridSelectionRangeBackgroundColor: "rgb(31 143 82 / 0.06)",
    gridSelectionCopiedBorderColor: "var(--sheets-app-accent)",
    gridSelectionCopiedBackgroundColor: "rgb(31 143 82 / 0.08)",
    gridSelectionFillPreviewBackgroundColor: "rgb(31 143 82 / 0.12)",
    gridSelectionMovePreviewBackgroundColor: "rgb(34 49 38 / 0.08)",
    gridSelectionAnchorBackgroundColor: "var(--sheets-app-accent)",
    gridSelectionActiveBorderColor: "var(--sheets-app-accent)",
    gridEditorBorderColor: "var(--sheets-app-accent)",
    gridEditorBackgroundColor: "var(--sheets-app-surface)",
    gridEditorFocusBorderColor: "var(--sheets-app-accent)",
    gridEditorFocusRingColor: "rgb(31 143 82 / 0.16)",
    gridEnumTriggerBorderColor: "var(--sheets-app-border)",
    gridEnumTriggerBackgroundColor: "var(--sheets-app-surface)",
    gridEnumTriggerTextColor: "var(--sheets-app-text-body)",
    gridEnumTriggerHoverBorderColor: "var(--sheets-app-accent)",
    gridEnumTriggerHoverBackgroundColor: "var(--sheets-app-accent-soft)",
    gridStickyBackgroundColor: "var(--sheets-app-surface)",
    gridStickyShadowColor: "rgb(21 34 25 / 0.08)",
    gridStickyRangeBackgroundColor: "rgb(31 143 82 / 0.08)",
    gridStickyRangeBorderColor: "var(--sheets-app-accent)",
    gridStickyAnchorBackgroundColor: "var(--sheets-app-accent)",
    gridStickyAnchorBorderColor: "var(--sheets-app-accent)",
    gridStickyActiveBorderColor: "var(--sheets-app-accent)",
    gridHeaderStickyBackgroundColor: "var(--sheets-app-surface-muted)",
    gridGroupStartGradientStart: "rgb(31 143 82 / 0.08)",
    gridGroupStartGradientEnd: "var(--sheets-app-surface-subtle)",
    gridGroupBadgeTextColor: "var(--sheets-app-text-muted)",
    gridSelectionOverlayBorderColor: "var(--sheets-app-accent)",
    gridSelectionOverlayBackgroundColor: "rgb(31 143 82 / 0.05)",
    gridSelectionOverlayFillBorderColor: "var(--sheets-app-accent)",
    gridSelectionOverlayFillBackgroundColor: "rgb(31 143 82 / 0.1)",
    gridSelectionOverlayMoveBorderColor: "var(--sheets-app-text-body)",
    gridSelectionOverlayMoveBackgroundColor: "rgb(34 49 38 / 0.08)",
    gridSelectionHandleBorderColor: "var(--sheets-app-accent-contrast)",
    gridSelectionHandleBackgroundColor: "var(--sheets-app-accent)",
    gridMoveHandleHoverBackgroundColor: "var(--sheets-app-accent)",
    gridHintBorderColor: "var(--sheets-app-border)",
    gridHintBackgroundColor: "#f7faf8",
    gridCopyMenuBorderColor: "var(--sheets-app-border)",
    gridCopyMenuBackgroundColor: "var(--sheets-app-surface)",
    gridCopyMenuShadowColor: "rgb(21 34 25 / 0.12)",
    gridCopyMenuItemHoverBorderColor: "var(--sheets-app-border)",
    gridCopyMenuItemHoverBackgroundColor: "var(--sheets-app-surface-muted)",
    gridColumnMenuBorderColor: "var(--sheets-app-border)",
    gridColumnMenuBackgroundColor: "var(--sheets-app-surface)",
    gridColumnMenuShadowColor: "rgb(21 34 25 / 0.12)",
    gridColumnMenuItemHoverBackgroundColor: "var(--sheets-app-surface-muted)",
    gridColumnMenuMutedTextColor: "#708074",
    gridColumnMenuFocusRingColor: "rgb(31 143 82 / 0.16)",
    gridColumnMenuSearchBorderColor: "var(--sheets-app-border)",
    gridColumnMenuSearchBackgroundColor: "#f8faf9",
  },
}
