import { toRgb, toRgba, transparent } from "./colorUtils"
import type { DataGridThemeTokens } from "./types"

const surface = "#ffffff"
const surfaceSubtle = "#f9fafb"
const surfaceMuted = "#f3f4f6"
const border = "#e5e7eb"
const borderStrong = "#d1d5db"
const text = "#111827"
const textMuted = "#6b7280"
const textSoft = "#9ca3af"
const accent = "#2563eb"
const accentSoft = "#eff6ff"
const accentMuted = "#dbeafe"

export const defaultThemeTokens: DataGridThemeTokens = {
  gridFontFamily: '"Arial", "Helvetica Neue", Helvetica, sans-serif',
  gridFontSize: "0.8125rem",
  gridTextColor: toRgb(text),
  gridBackgroundColor: toRgb(surface),
  gridTextPrimary: toRgb(text),
  gridTextMuted: toRgb(textMuted),
  gridTextSoft: toRgb(textSoft),
  gridGlassBorder: toRgb(border),
  gridAccentStrong: toRgb(accent),
  headerBackgroundColor: toRgb(surfaceMuted),
  headerTextColor: toRgb(text),
  headerBorderColor: toRgb(borderStrong),
  headerPaddingX: "0.75rem",
  headerPaddingY: "0.375rem",
  headerHighlightBorderColor: toRgb(accent),
  headerHighlightTextColor: toRgb(text),
  headerSelectedTextColor: toRgb(text),
  headerSystemTextColor: toRgb(textMuted),
  bodyRowBackgroundColor: toRgb(surface),
  bodyRowTextColor: toRgb(text),
  bodyRowHoverBackgroundColor: toRgb(surfaceSubtle),
  bodyRowSelectedBackgroundColor: toRgb(accentSoft),
  bodyRowSelectedTextColor: toRgb(text),
  bodyCellPaddingX: "0.625rem",
  bodyCellPaddingY: "0rem",
  bodyCellBorderColor: toRgb(border),
  selectionCellBackgroundColor: toRgb(accentSoft),
  selectionCellTextColor: toRgb(text),
  indexCellBackgroundColor: toRgb(surfaceMuted),
  indexCellTextColor: toRgb(textMuted),
  rowDividerSize: "1px",
  rowDividerColor: toRgb(border),
  columnDividerSize: "1px",
  columnDividerColor: toRgb(border),
  headerDividerSize: "1px",
  headerDividerColor: toRgb(borderStrong),
  summaryDividerSize: "1px",
  summaryDividerColor: toRgb(border),
  groupRowBackgroundColor: toRgb(surfaceSubtle),
  groupRowTextColor: toRgb(text),
  summaryRowBackgroundColor: toRgb(surfaceMuted),
  summaryRowTextColor: toRgb(text),
  summaryLabelTextColor: toRgb(textMuted),
  pinnedBackgroundColor: toRgb(surface),
  pinnedLeftBackgroundColor: toRgb(surface),
  pinnedRightBackgroundColor: toRgb(surface),
  pinnedShadow: `0 0 0 0 ${transparent()}`,
  pinnedLeftShadow: `inset -1px 0 0 ${toRgb(borderStrong)}`,
  pinnedRightShadow: `inset 1px 0 0 ${toRgb(borderStrong)}`,
  pinnedLeftBorderColor: toRgb(borderStrong),
  pinnedLeftBorderWidth: "1px",
  pinnedRightBorderColor: toRgb(borderStrong),
  pinnedRightBorderWidth: "1px",
  gridHeroBackgroundStart: toRgb(surface),
  gridHeroBackgroundEnd: toRgb(surfaceMuted),
  gridChipBackground: toRgb(surfaceMuted),
  gridControlsBackground: toRgb(surface),
  gridControlsInputBackground: toRgb(surface),
  gridControlsSurfaceBackground: toRgb(surface),
  gridFilterPanelBorderColor: toRgb(borderStrong),
  gridFilterPanelBackground: toRgb(surface),
  gridFilterIndicatorActiveColor: toRgb(accent),
  gridMetricsCardBackground: toRgb(surface),
  gridViewportBackground: toRgb(surface),
  gridFocusOutlineColor: toRgb(accent),
  gridHeaderRowBackgroundColor: toRgb(surfaceMuted),
  gridHeaderCellBackgroundColor: toRgb(surfaceMuted),
  gridHeaderCellHoverBackgroundColor: toRgb(surfaceSubtle),
  gridHeaderFilterOpenBackgroundColor: toRgb(accentSoft),
  gridGroupRowBorderColor: toRgb(borderStrong),
  gridRowSelectedStickyBackgroundColor: toRgb(accentSoft),
  gridRowSelectedRangeBackgroundColor: toRgb(accentMuted),
  gridCheckboxAccentColor: toRgb(accent),
  gridSortIndicatorColor: toRgb(accent),
  gridSortPriorityBorderColor: toRgb(borderStrong),
  gridHeaderFilterHighlightColor: toRgb(accent),
  gridFilterTriggerBorderColor: toRgb(borderStrong),
  gridFilterTriggerBackgroundColor: toRgb(surface),
  gridFilterTriggerHoverBorderColor: toRgb(accent),
  gridFilterTriggerHoverTextColor: toRgb(text),
  gridFilterTriggerActiveBorderColor: toRgb(accent),
  gridFilterTriggerActiveBackgroundColor: toRgb(accentSoft),
  gridFilterTriggerActiveTextColor: toRgb(text),
  gridResizeHandleHoverColor: toRgb(accent),
  gridNumericTextColor: toRgb(text),
  gridEditableHoverBackgroundColor: toRgb(surfaceSubtle),
  gridSelectionRangeBackgroundColor: toRgba(accent, 0.12),
  gridSelectionCopiedBorderColor: toRgb(accent),
  gridSelectionCopiedBackgroundColor: toRgba(accent, 0.08),
  gridSelectionFillPreviewBackgroundColor: toRgba(accent, 0.1),
  gridSelectionMovePreviewBackgroundColor: toRgba(textMuted, 0.1),
  gridSelectionAnchorBackgroundColor: toRgba(accent, 0.16),
  gridSelectionActiveBorderColor: toRgb(accent),
  gridEditorBorderColor: toRgb(borderStrong),
  gridEditorBackgroundColor: toRgb(surface),
  gridEditorFocusBorderColor: toRgb(accent),
  gridEditorFocusRingColor: toRgba(accent, 0.16),
  gridEnumTriggerBorderColor: toRgb(borderStrong),
  gridEnumTriggerBackgroundColor: toRgb(surface),
  gridEnumTriggerTextColor: toRgb(text),
  gridEnumTriggerHoverBorderColor: toRgb(accent),
  gridEnumTriggerHoverBackgroundColor: toRgb(surfaceSubtle),
  gridStickyBackgroundColor: toRgb(surface),
  gridStickyShadowColor: toRgba(text, 0.12),
  gridStickyRangeBackgroundColor: toRgb(accentSoft),
  gridStickyRangeBorderColor: toRgb(accent),
  gridStickyAnchorBackgroundColor: toRgb(accentMuted),
  gridStickyAnchorBorderColor: toRgb(accent),
  gridStickyActiveBorderColor: toRgb(accent),
  gridHeaderStickyBackgroundColor: toRgb(surfaceMuted),
  gridGroupStartGradientStart: toRgb(surfaceSubtle),
  gridGroupStartGradientEnd: toRgb(surfaceSubtle),
  gridGroupBadgeTextColor: toRgb(textMuted),
  gridSelectionOverlayBorderColor: toRgb(accent),
  gridSelectionOverlayBackgroundColor: toRgba(accent, 0.06),
  gridSelectionOverlayFillBorderColor: toRgb(accent),
  gridSelectionOverlayFillBackgroundColor: toRgba(accent, 0.05),
  gridSelectionOverlayMoveBorderColor: toRgb(textMuted),
  gridSelectionOverlayMoveBackgroundColor: toRgba(textMuted, 0.06),
  gridSelectionHandleBorderColor: toRgb(surface),
  gridSelectionHandleBackgroundColor: toRgb(accent),
  gridMoveHandleHoverBackgroundColor: toRgba(accent, 0.1),
  gridHintBorderColor: toRgb(border),
  gridHintBackgroundColor: toRgb(surfaceSubtle),
  gridCopyMenuBorderColor: toRgb(borderStrong),
  gridCopyMenuBackgroundColor: toRgb(surface),
  gridCopyMenuShadowColor: toRgba(text, 0.14),
  gridCopyMenuItemHoverBorderColor: toRgb(borderStrong),
  gridCopyMenuItemHoverBackgroundColor: toRgb(surfaceSubtle),
  gridColumnMenuBorderColor: toRgb(borderStrong),
  gridColumnMenuBackgroundColor: toRgb(surface),
  gridColumnMenuShadowColor: toRgba(text, 0.14),
  gridColumnMenuItemHoverBackgroundColor: toRgb(surfaceSubtle),
  gridColumnMenuMutedTextColor: toRgb(textMuted),
  gridColumnMenuFocusRingColor: toRgba(accent, 0.16),
  gridColumnMenuSearchBorderColor: toRgb(borderStrong),
  gridColumnMenuSearchBackgroundColor: toRgb(surface),
}
