import { createThemePresetTokens } from "./themePresetFactory"
import type { DataGridStyleConfig } from "./types"

const industrialFont =
  '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace'

const light = createThemePresetTokens({
  fontFamily: industrialFont,
  fontSize: "0.765rem",
  text: "#1f2937",
  textMuted: "#4b5563",
  textSoft: "#6b7280",
  background: "#f3f4f6",
  viewport: "#f8fafc",
  surface: "#f8fafc",
  surfaceSubtle: "#eef2f7",
  surfaceMuted: "#e5e7eb",
  surfaceRaised: "#ffffff",
  header: "#e5e7eb",
  headerHover: "#dbe3ee",
  headerOpen: "#d4e9f7",
  border: "#cbd5e1",
  borderStrong: "#94a3b8",
  accent: "#0891b2",
  accentStrong: "#0e7490",
  accentSoft: "#cffafe",
  accentMuted: "#a5f3fc",
  accentText: "#155e75",
  groupBackground: "#e2e8f0",
  groupText: "#334155",
  summaryBackground: "#dbe3ee",
  summaryText: "#1f2937",
  pinnedBackground: "#eef2f7",
  shadow: "#0f172a",
  rowHover: "#eef6fb",
  rowSelected: "#dff6fb",
  numericText: "#0f766e",
  headerPaddingX: "0.5rem",
  headerPaddingY: "0.25rem",
  bodyCellPaddingX: "0.5rem",
  bodyCellPaddingY: "0rem",
})

const dark = createThemePresetTokens({
  fontFamily: industrialFont,
  fontSize: "0.765rem",
  text: "#dbeafe",
  textMuted: "#94a3b8",
  textSoft: "#64748b",
  background: "#07111c",
  viewport: "#0b1623",
  surface: "#0b1623",
  surfaceSubtle: "#122033",
  surfaceMuted: "#111827",
  surfaceRaised: "#101b2e",
  header: "#111827",
  headerHover: "#16233a",
  headerOpen: "#083344",
  border: "#26384f",
  borderStrong: "#3f5875",
  accent: "#22d3ee",
  accentStrong: "#67e8f9",
  accentSoft: "#083344",
  accentMuted: "#164e63",
  accentText: "#a5f3fc",
  groupBackground: "#111c2d",
  groupText: "#cbd5e1",
  summaryBackground: "#101b2e",
  summaryText: "#e2e8f0",
  pinnedBackground: "#0d1828",
  shadow: "#000000",
  rowHover: "#122033",
  rowSelected: "#083344",
  numericText: "#5eead4",
  headerPaddingX: "0.5rem",
  headerPaddingY: "0.25rem",
  bodyCellPaddingX: "0.5rem",
  bodyCellPaddingY: "0rem",
})

/** Compact engineering preset for dense operational grids. */
export const industrialNeutralTheme: DataGridStyleConfig = {
  inheritThemeFromDocument: true,
  defaultTokenVariant: "light",
  tokens: light,
  tokenVariants: {
    light,
    dark,
  },
}
