import { palette } from "./palette"
import { toRgb, toRgba, transparent } from "./colorUtils"
import type { DataGridStyleConfig, DataGridThemeTokens } from "./types"

const lightUiTokens: Partial<DataGridThemeTokens> = {
  gridTextPrimary: toRgb(palette.slate800),
  gridTextMuted: toRgba(palette.slate800, 0.7),
  gridTextSoft: toRgba(palette.slate800, 0.55),
  gridGlassBorder: toRgba(palette.gray300, 0.6),
  gridAccentStrong: toRgb(palette.blue600),
  gridHeroBackgroundStart: toRgba(palette.gray100, 0.9),
  gridHeroBackgroundEnd: toRgba(palette.gray50, 0.96),
  gridChipBackground: toRgba(palette.gray100, 0.7),
  gridControlsBackground: toRgba(palette.gray50, 0.95),
  gridControlsInputBackground: toRgba(palette.white, 0.95),
  gridControlsSurfaceBackground: toRgba(palette.white, 0.98),
  gridFilterPanelBorderColor: toRgba(palette.blue300, 0.35),
  gridFilterPanelBackground: toRgba(palette.white, 0.98),
  gridFilterIndicatorActiveColor: toRgb(palette.blue600),
  gridMetricsCardBackground: toRgba(palette.gray50, 0.96),
  gridViewportBackground: toRgb(palette.white),
  gridFocusOutlineColor: toRgba(palette.blue500, 0.7),
  gridHeaderRowBackgroundColor: toRgb(palette.gray100),
  gridHeaderCellBackgroundColor: toRgb(palette.gray150),
  gridHeaderCellHoverBackgroundColor: toRgb(palette.gray200),
  gridHeaderFilterOpenBackgroundColor: toRgb(palette.gray200),
  gridGroupRowBorderColor: toRgba(palette.blue400, 0.45),
  gridRowSelectedStickyBackgroundColor: toRgba(palette.blue200, 0.6),
  gridRowSelectedRangeBackgroundColor: toRgba(palette.blue200, 0.35),
  gridCheckboxAccentColor: toRgb(palette.blue600),
  gridSortIndicatorColor: toRgb(palette.blue600),
  gridSortPriorityBorderColor: toRgba(palette.blue400, 0.45),
  gridHeaderFilterHighlightColor: toRgba(palette.blue500, 0.6),
  gridFilterTriggerBorderColor: toRgba(palette.gray400, 0.4),
  gridFilterTriggerBackgroundColor: toRgba(palette.gray50, 0.95),
  gridFilterTriggerHoverBorderColor: toRgba(palette.blue500, 0.7),
  gridFilterTriggerHoverTextColor: toRgb(palette.blue600),
  gridFilterTriggerActiveBorderColor: toRgba(palette.blue500, 0.8),
  gridFilterTriggerActiveBackgroundColor: toRgba(palette.blue200, 0.7),
  gridFilterTriggerActiveTextColor: toRgb(palette.blue600),
  gridResizeHandleHoverColor: toRgba(palette.blue500, 0.8),
  gridNumericTextColor: toRgb(palette.blue600),
  gridEditableHoverBackgroundColor: toRgba(palette.blue200, 0.3),
  gridSelectionRangeBackgroundColor: toRgba(palette.blue200, 0.35),
  gridSelectionCopiedBorderColor: toRgba(palette.blue300, 0.7),
  gridSelectionCopiedBackgroundColor: toRgba(palette.blue200, 0.3),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.blue200, 0.25),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.blue300, 0.25),
  gridSelectionAnchorBackgroundColor: toRgba(palette.blue200, 0.4),
  gridSelectionActiveBorderColor: toRgba(palette.blue500, 0.8),
  gridEditorBorderColor: toRgba(palette.gray400, 0.5),
  gridEditorBackgroundColor: toRgb(palette.white),
  gridEditorFocusBorderColor: toRgba(palette.blue500, 0.8),
  gridEditorFocusRingColor: toRgba(palette.blue500, 0.25),
  gridEnumTriggerBorderColor: toRgba(palette.gray400, 0.5),
  gridEnumTriggerBackgroundColor: toRgb(palette.white),
  gridEnumTriggerTextColor: toRgb(palette.blue600),
  gridEnumTriggerHoverBorderColor: toRgba(palette.blue500, 0.8),
  gridEnumTriggerHoverBackgroundColor: toRgba(palette.blue200, 0.5),
  gridStickyBackgroundColor: toRgba(palette.gray50, 0.98),
  gridStickyShadowColor: toRgba(palette.gray400, 0.25),
  gridStickyRangeBackgroundColor: toRgba(palette.blue200, 0.45),
  gridStickyRangeBorderColor: toRgba(palette.blue400, 0.5),
  gridStickyAnchorBackgroundColor: toRgba(palette.blue200, 0.6),
  gridStickyAnchorBorderColor: toRgba(palette.blue400, 0.7),
  gridStickyActiveBorderColor: toRgba(palette.blue500, 0.85),
  gridHeaderStickyBackgroundColor: toRgba(palette.gray150, 0.98),
  gridGroupStartGradientStart: toRgba(palette.blue200, 0.35),
  gridGroupStartGradientEnd: toRgba(palette.gray50, 0.98),
  gridGroupBadgeTextColor: toRgb(palette.blue600),
  gridSelectionOverlayBorderColor: toRgba(palette.blue500, 0.8),
  gridSelectionOverlayBackgroundColor: toRgba(palette.blue200, 0.25),
  gridSelectionOverlayFillBorderColor: toRgba(palette.blue500, 0.7),
  gridSelectionOverlayFillBackgroundColor: toRgba(palette.blue200, 0.2),
  gridSelectionOverlayMoveBorderColor: toRgba(palette.blue400, 0.7),
  gridSelectionOverlayMoveBackgroundColor: toRgba(palette.blue200, 0.18),
  gridSelectionHandleBorderColor: toRgba(palette.blue500, 0.8),
  gridSelectionHandleBackgroundColor: toRgba(palette.blue600, 0.9),
  gridMoveHandleHoverBackgroundColor: toRgba(palette.blue200, 0.4),
  gridHintBorderColor: toRgba(palette.gray300, 0.6),
  gridHintBackgroundColor: toRgba(palette.gray50, 0.95),
  gridCopyMenuBorderColor: toRgba(palette.blue300, 0.4),
  gridCopyMenuBackgroundColor: toRgba(palette.white, 0.98),
  gridCopyMenuShadowColor: toRgba(palette.gray400, 0.2),
  gridCopyMenuItemHoverBorderColor: toRgba(palette.blue400, 0.4),
  gridCopyMenuItemHoverBackgroundColor: toRgba(palette.blue200, 0.4),
}

const darkUiTokens: Partial<DataGridThemeTokens> = {
  gridTextPrimary: toRgb(palette.gray100),
  gridTextMuted: toRgba(palette.gray200, 0.75),
  gridTextSoft: toRgba(palette.gray200, 0.6),
  gridGlassBorder: toRgba(palette.slate600, 0.4),
  gridAccentStrong: toRgb(palette.blue400),
  gridHeroBackgroundStart: toRgba(palette.slate900, 0.94),
  gridHeroBackgroundEnd: toRgba(palette.slate850, 0.92),
  gridChipBackground: toRgba(palette.gray200, 0.08),
  gridControlsBackground: toRgba(palette.slate900, 0.9),
  gridControlsInputBackground: toRgba(palette.slate800, 0.5),
  gridControlsSurfaceBackground: toRgba(palette.slate850, 0.98),
  gridFilterPanelBorderColor: toRgba(palette.blue300, 0.35),
  gridFilterPanelBackground: toRgba(palette.slate850, 0.96),
  gridFilterIndicatorActiveColor: toRgba(palette.blue300, 0.95),
  gridMetricsCardBackground: toRgba(palette.slate900, 0.9),
  gridViewportBackground: toRgba(palette.slate900, 0.95),
  gridFocusOutlineColor: toRgba(palette.blue400, 0.6),
  gridHeaderRowBackgroundColor: toRgba(palette.slate850, 0.98),
  gridHeaderCellBackgroundColor: toRgba(palette.slate800, 0.98),
  gridHeaderCellHoverBackgroundColor: toRgba(palette.slate700, 0.92),
  gridHeaderFilterOpenBackgroundColor: toRgba(palette.slate700, 0.95),
  gridGroupRowBorderColor: toRgba(palette.blue300, 0.45),
  gridRowSelectedStickyBackgroundColor: toRgba(palette.blue400, 0.32),
  gridRowSelectedRangeBackgroundColor: toRgba(palette.blue400, 0.22),
  gridCheckboxAccentColor: toRgb(palette.blue400),
  gridSortIndicatorColor: toRgba(palette.blue300, 0.95),
  gridSortPriorityBorderColor: toRgba(palette.blue300, 0.45),
  gridHeaderFilterHighlightColor: toRgba(palette.blue400, 0.6),
  gridFilterTriggerBorderColor: toRgba(palette.slate500, 0.45),
  gridFilterTriggerBackgroundColor: toRgba(palette.slate800, 0.92),
  gridFilterTriggerHoverBorderColor: toRgba(palette.blue300, 0.8),
  gridFilterTriggerHoverTextColor: toRgba(palette.blue200, 0.95),
  gridFilterTriggerActiveBorderColor: toRgba(palette.blue300, 0.85),
  gridFilterTriggerActiveBackgroundColor: toRgba(palette.blue400, 0.28),
  gridFilterTriggerActiveTextColor: toRgba(palette.blue200, 1),
  gridResizeHandleHoverColor: toRgba(palette.blue300, 0.9),
  gridNumericTextColor: toRgb(palette.blue200),
  gridEditableHoverBackgroundColor: toRgba(palette.slate700, 0.6),
  gridSelectionRangeBackgroundColor: toRgba(palette.blue400, 0.2),
  gridSelectionCopiedBorderColor: toRgba(palette.blue300, 0.85),
  gridSelectionCopiedBackgroundColor: toRgba(palette.blue400, 0.12),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.blue300, 0.16),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.blue300, 0.18),
  gridSelectionAnchorBackgroundColor: toRgba(palette.blue400, 0.24),
  gridSelectionActiveBorderColor: toRgba(palette.blue200, 0.9),
  gridEditorBorderColor: toRgba(palette.slate500, 0.4),
  gridEditorBackgroundColor: toRgba(palette.slate800, 0.96),
  gridEditorFocusBorderColor: toRgba(palette.blue300, 0.75),
  gridEditorFocusRingColor: toRgba(palette.blue400, 0.25),
  gridEnumTriggerBorderColor: toRgba(palette.slate500, 0.4),
  gridEnumTriggerBackgroundColor: toRgba(palette.slate800, 0.95),
  gridEnumTriggerTextColor: toRgba(palette.blue200, 0.95),
  gridEnumTriggerHoverBorderColor: toRgba(palette.blue300, 0.8),
  gridEnumTriggerHoverBackgroundColor: toRgba(palette.slate700, 0.9),
  gridStickyBackgroundColor: toRgba(palette.slate850, 0.98),
  gridStickyShadowColor: toRgba(palette.slate500, 0.3),
  gridStickyRangeBackgroundColor: toRgba(palette.blue400, 0.26),
  gridStickyRangeBorderColor: toRgba(palette.blue300, 0.55),
  gridStickyAnchorBackgroundColor: toRgba(palette.blue400, 0.32),
  gridStickyAnchorBorderColor: toRgba(palette.blue200, 0.8),
  gridStickyActiveBorderColor: toRgba(palette.blue200, 1),
  gridHeaderStickyBackgroundColor: toRgba(palette.slate800, 0.99),
  gridGroupStartGradientStart: toRgba(palette.blue400, 0.18),
  gridGroupStartGradientEnd: toRgba(palette.slate900, 0.95),
  gridGroupBadgeTextColor: toRgba(palette.blue200, 0.95),
  gridSelectionOverlayBorderColor: toRgba(palette.blue400, 0.9),
  gridSelectionOverlayBackgroundColor: toRgba(palette.blue400, 0.1),
  gridSelectionOverlayFillBorderColor: toRgba(palette.blue300, 0.9),
  gridSelectionOverlayFillBackgroundColor: toRgba(palette.blue400, 0.08),
  gridSelectionOverlayMoveBorderColor: toRgba(palette.blue300, 0.9),
  gridSelectionOverlayMoveBackgroundColor: toRgba(palette.blue400, 0.08),
  gridSelectionHandleBorderColor: toRgba(palette.blue300, 0.95),
  gridSelectionHandleBackgroundColor: toRgba(palette.blue400, 0.9),
  gridMoveHandleHoverBackgroundColor: toRgba(palette.blue300, 0.2),
  gridHintBorderColor: toRgba(palette.slate600, 0.3),
  gridHintBackgroundColor: toRgba(palette.slate900, 0.88),
  gridCopyMenuBorderColor: toRgba(palette.blue300, 0.35),
  gridCopyMenuBackgroundColor: toRgba(palette.slate850, 0.97),
  gridCopyMenuShadowColor: toRgba(palette.black, 0.35),
  gridCopyMenuItemHoverBorderColor: toRgba(palette.blue300, 0.4),
  gridCopyMenuItemHoverBackgroundColor: toRgba(palette.slate700, 0.8),
}

/**
 * Industrial neutral preset used as the default house style for the headless table demo.
 */
export const industrialNeutralTheme: DataGridStyleConfig = {
  inheritThemeFromDocument: true,
  defaultTokenVariant: "light",
  activeTokenVariant: "light",
  tokenVariants: {
    light: {
      gridFontFamily:
        '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      gridFontSize: "0.78rem",
      gridTextColor: toRgb(palette.slate800),
      gridBackgroundColor: toRgb(palette.white),
      headerBackgroundColor: toRgb(palette.gray150),
      headerTextColor: toRgb(palette.zinc600),
      headerBorderColor: toRgb(palette.gray200),
      headerPaddingX: "0.75rem",
      headerPaddingY: "0.5rem",
      bodyRowBackgroundColor: toRgb(palette.white),
      bodyRowTextColor: toRgb(palette.slate800),
      bodyRowHoverBackgroundColor: toRgba(palette.blue500, 0.08),
      bodyRowSelectedBackgroundColor: toRgba(palette.blue500, 0.18),
      bodyRowSelectedTextColor: toRgb(palette.slate800),
      bodyCellPaddingX: "0.75rem",
      bodyCellPaddingY: "0.375rem",
      bodyCellBorderColor: toRgb(palette.gray200),
      selectionCellBackgroundColor: toRgb(palette.gray150),
      selectionCellTextColor: toRgb(palette.slate800),
      indexCellBackgroundColor: toRgb(palette.gray150),
      indexCellTextColor: toRgb(palette.slate500),
      rowDividerSize: "1px",
      rowDividerColor: toRgb(palette.gray200),
      columnDividerSize: "1px",
      columnDividerColor: toRgb(palette.gray200),
      headerDividerSize: "1px",
      headerDividerColor: toRgb(palette.gray200),
      summaryDividerSize: "1px",
      summaryDividerColor: toRgb(palette.gray200),
      groupRowBackgroundColor: toRgba(palette.gray150, 0.85),
      groupRowTextColor: toRgb(palette.zinc600),
      summaryRowBackgroundColor: toRgb(palette.gray150),
      summaryRowTextColor: toRgb(palette.slate600),
      summaryLabelTextColor: toRgb(palette.slate500),
      pinnedBackgroundColor: toRgb(palette.gray50),
      pinnedLeftBackgroundColor: toRgb(palette.gray50),
      pinnedRightBackgroundColor: toRgb(palette.gray50),
      pinnedShadow: `0 0 0 0 ${transparent()}`,
      pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.slate400, 0.35)}`,
      pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.slate400, 0.35)}`,
      pinnedLeftBorderColor: toRgb(palette.slate400),
      pinnedLeftBorderWidth: "1px",
      pinnedRightBorderColor: toRgb(palette.slate400),
      pinnedRightBorderWidth: "1px",
      ...lightUiTokens,
    },
    dark: {
      gridFontFamily:
        '"IBM Plex Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      gridFontSize: "0.78rem",
      gridTextColor: toRgb(palette.gray200),
      gridBackgroundColor: toRgb(palette.slate900),
      headerBackgroundColor: toRgb(palette.slate800),
      headerTextColor: toRgb(palette.gray200),
      headerBorderColor: toRgb(palette.slate700),
      headerPaddingX: "0.75rem",
      headerPaddingY: "0.5rem",
      bodyRowBackgroundColor: toRgb(palette.slate900),
      bodyRowTextColor: toRgb(palette.gray200),
      bodyRowHoverBackgroundColor: toRgba(palette.blue400, 0.16),
      bodyRowSelectedBackgroundColor: toRgba(palette.blue400, 0.32),
      bodyRowSelectedTextColor: toRgb(palette.gray50),
      bodyCellPaddingX: "0.75rem",
      bodyCellPaddingY: "0.375rem",
      bodyCellBorderColor: toRgb(palette.slate800),
      selectionCellBackgroundColor: toRgb(palette.slate800),
      selectionCellTextColor: toRgb(palette.gray50),
      indexCellBackgroundColor: toRgb(palette.slate800),
      indexCellTextColor: toRgb(palette.gray400),
      rowDividerSize: "1px",
      rowDividerColor: toRgb(palette.slate800),
      columnDividerSize: "1px",
      columnDividerColor: toRgb(palette.slate800),
      headerDividerSize: "1px",
      headerDividerColor: toRgb(palette.slate700),
      summaryDividerSize: "1px",
      summaryDividerColor: toRgb(palette.slate800),
      groupRowBackgroundColor: toRgba(palette.slate800, 0.9),
      groupRowTextColor: toRgb(palette.gray300),
      summaryRowBackgroundColor: toRgb(palette.slate800),
      summaryRowTextColor: toRgb(palette.gray100),
      summaryLabelTextColor: toRgb(palette.gray400),
      pinnedBackgroundColor: toRgb(palette.slate900),
      pinnedLeftBackgroundColor: toRgb(palette.slate850),
      pinnedRightBackgroundColor: toRgb(palette.slate850),
      pinnedShadow: `0 0 0 0 ${transparent()}`,
      pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.slate500, 0.45)}`,
      pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.slate500, 0.45)}`,
      pinnedLeftBorderColor: toRgb(palette.slate500),
      pinnedLeftBorderWidth: "1px",
      pinnedRightBorderColor: toRgb(palette.slate500),
      pinnedRightBorderWidth: "1px",
      ...darkUiTokens,
    },
  },
  body: {
    row: "selectable-row selectable-row--idle",
  },
  state: {
    selectedRow: "selectable-row selectable-row--selected",
  },
}
