import { createThemePresetTokens } from "./themePresetFactory"
import type { DataGridStyleConfig } from "./types"

const sugarFont = '"Inter", "Segoe UI", Arial, sans-serif'

const light = createThemePresetTokens({
  fontFamily: sugarFont,
  fontSize: "0.84rem",
  text: "#35243f",
  textMuted: "#7c667f",
  textSoft: "#9f879a",
  background: "#fff7fb",
  viewport: "#fffafd",
  surface: "#fffafd",
  surfaceSubtle: "#fff1f7",
  surfaceMuted: "#fde7f0",
  surfaceRaised: "#ffffff",
  header: "#fde7f0",
  headerHover: "#fce0ec",
  headerOpen: "#f4e8ff",
  border: "#f3cadb",
  borderStrong: "#dfa7c0",
  accent: "#db2777",
  accentStrong: "#be185d",
  accentSoft: "#fce7f3",
  accentMuted: "#fbcfe8",
  accentText: "#9d174d",
  groupBackground: "#fff1f7",
  groupText: "#7e3157",
  summaryBackground: "#fde7f0",
  summaryText: "#35243f",
  pinnedBackground: "#fff7fb",
  shadow: "#4a2838",
  rowHover: "#fff1f7",
  rowSelected: "#fce7f3",
  numericText: "#7c3aed",
  headerPaddingX: "0.8125rem",
  headerPaddingY: "0.4375rem",
  bodyCellPaddingX: "0.75rem",
  bodyCellPaddingY: "0rem",
})

const dark = createThemePresetTokens({
  fontFamily: sugarFont,
  fontSize: "0.84rem",
  text: "#fdeff7",
  textMuted: "#e9b8d0",
  textSoft: "#c98cab",
  background: "#21111b",
  viewport: "#261522",
  surface: "#261522",
  surfaceSubtle: "#321b2c",
  surfaceMuted: "#2b1726",
  surfaceRaised: "#321b2c",
  header: "#2b1726",
  headerHover: "#3a2033",
  headerOpen: "#4a1d3a",
  border: "#5a3147",
  borderStrong: "#7a4560",
  accent: "#f472b6",
  accentStrong: "#f9a8d4",
  accentSoft: "#4a1d3a",
  accentMuted: "#831843",
  accentText: "#fbcfe8",
  groupBackground: "#321b2c",
  groupText: "#f3c5d9",
  summaryBackground: "#2b1726",
  summaryText: "#fdeff7",
  pinnedBackground: "#261522",
  shadow: "#000000",
  rowHover: "#321b2c",
  rowSelected: "#4a1d3a",
  numericText: "#c4b5fd",
  headerPaddingX: "0.8125rem",
  headerPaddingY: "0.4375rem",
  bodyCellPaddingX: "0.75rem",
  bodyCellPaddingY: "0rem",
})

/** Soft expressive preset for users who want a warmer workspace. */
export const sugarTheme: DataGridStyleConfig = {
  inheritThemeFromDocument: true,
  defaultTokenVariant: "light",
  tokens: light,
  tokenVariants: {
    light,
    dark,
  },
}
