import { palette } from "./palette"
import { toRgb, toRgba } from "./colorUtils"
import type { DataGridStyleConfig, DataGridThemeTokens } from "./types"

const lightTokens: Partial<DataGridThemeTokens> = {
  gridFontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  gridFontSize: "0.86rem",
  gridTextColor: toRgb(palette.slate800),
  gridTextPrimary: toRgb(palette.slate900),
  gridTextMuted: toRgba(palette.slate700, 0.7),
  gridTextSoft: toRgba(palette.slate700, 0.55),
  gridBackgroundColor: toRgb(palette.white),
  gridViewportBackground: toRgb(palette.gray50),
  gridGlassBorder: toRgba(palette.gray300, 0.7),
  gridAccentStrong: toRgb(palette.blue600),
  gridHeaderRowBackgroundColor: toRgb(palette.gray100),
  gridHeaderCellBackgroundColor: toRgb(palette.gray100),
  gridHeaderCellHoverBackgroundColor: toRgb(palette.gray200),
  headerBackgroundColor: toRgb(palette.gray100),
  headerTextColor: toRgb(palette.zinc600),
  headerBorderColor: toRgba(palette.gray300, 0.8),
  bodyRowBackgroundColor: toRgb(palette.white),
  bodyRowTextColor: toRgb(palette.slate800),
  bodyRowHoverBackgroundColor: toRgba(palette.blue400, 0.08),
  bodyRowSelectedBackgroundColor: toRgba(palette.blue400, 0.18),
  bodyRowSelectedTextColor: toRgb(palette.slate800),
  bodyCellBorderColor: toRgba(palette.gray300, 0.8),
  rowDividerColor: toRgba(palette.gray300, 0.7),
  rowDividerSize: "1px",
  columnDividerColor: toRgba(palette.gray300, 0.7),
  columnDividerSize: "1px",
  headerDividerColor: toRgba(palette.gray300, 0.9),
  headerDividerSize: "1px",
  gridSelectionRangeBackgroundColor: toRgba(palette.blue400, 0.14),
  gridSelectionActiveBorderColor: toRgba(palette.blue500, 0.7),
  gridSelectionHandleBackgroundColor: toRgb(palette.blue500),
  gridSelectionHandleBorderColor: toRgba(palette.blue500, 0.85),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.blue400, 0.12),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.blue400, 0.16),
  gridEditorBackgroundColor: toRgb(palette.white),
  gridEditorBorderColor: toRgba(palette.gray400, 0.6),
  gridEditorFocusBorderColor: toRgba(palette.blue500, 0.8),
  gridEditorFocusRingColor: toRgba(palette.blue500, 0.2),
  gridResizeHandleHoverColor: toRgba(palette.blue500, 0.8),
  gridSortIndicatorColor: toRgb(palette.blue600),
  gridSortPriorityBorderColor: toRgba(palette.blue400, 0.4),
  gridCheckboxAccentColor: toRgb(palette.blue600),
  gridStickyBackgroundColor: toRgba(palette.gray100, 0.98),
  gridStickyShadowColor: toRgba(palette.gray400, 0.28),
  gridHeaderStickyBackgroundColor: toRgba(palette.gray100, 0.98),
}

const darkTokens: Partial<DataGridThemeTokens> = {
  gridFontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  gridFontSize: "0.86rem",
  gridTextColor: toRgb(palette.gray100),
  gridTextPrimary: toRgb(palette.gray50),
  gridTextMuted: toRgba(palette.gray200, 0.75),
  gridTextSoft: toRgba(palette.gray200, 0.55),
  gridBackgroundColor: toRgb(palette.midnight950),
  gridViewportBackground: toRgba(palette.slate900, 0.96),
  gridGlassBorder: toRgba(palette.slate600, 0.5),
  gridAccentStrong: toRgb(palette.blue400),
  gridHeaderRowBackgroundColor: toRgba(palette.slate850, 0.98),
  gridHeaderCellBackgroundColor: toRgba(palette.slate850, 0.98),
  gridHeaderCellHoverBackgroundColor: toRgba(palette.slate700, 0.9),
  headerBackgroundColor: toRgba(palette.slate850, 0.98),
  headerTextColor: toRgba(palette.gray200, 0.9),
  headerBorderColor: toRgba(palette.slate600, 0.6),
  bodyRowBackgroundColor: toRgba(palette.slate900, 0.96),
  bodyRowTextColor: toRgb(palette.gray100),
  bodyRowHoverBackgroundColor: toRgba(palette.blue400, 0.14),
  bodyRowSelectedBackgroundColor: toRgba(palette.blue400, 0.24),
  bodyRowSelectedTextColor: toRgb(palette.gray100),
  bodyCellBorderColor: toRgba(palette.slate600, 0.6),
  rowDividerColor: toRgba(palette.slate600, 0.55),
  rowDividerSize: "1px",
  columnDividerColor: toRgba(palette.slate600, 0.55),
  columnDividerSize: "1px",
  headerDividerColor: toRgba(palette.slate600, 0.7),
  headerDividerSize: "1px",
  gridSelectionRangeBackgroundColor: toRgba(palette.blue400, 0.18),
  gridSelectionActiveBorderColor: toRgba(palette.blue300, 0.85),
  gridSelectionHandleBackgroundColor: toRgb(palette.blue400),
  gridSelectionHandleBorderColor: toRgba(palette.blue300, 0.9),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.blue400, 0.16),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.blue400, 0.2),
  gridEditorBackgroundColor: toRgba(palette.slate800, 0.96),
  gridEditorBorderColor: toRgba(palette.slate500, 0.6),
  gridEditorFocusBorderColor: toRgba(palette.blue300, 0.85),
  gridEditorFocusRingColor: toRgba(palette.blue400, 0.25),
  gridResizeHandleHoverColor: toRgba(palette.blue300, 0.85),
  gridSortIndicatorColor: toRgba(palette.blue300, 0.95),
  gridSortPriorityBorderColor: toRgba(palette.blue300, 0.45),
  gridCheckboxAccentColor: toRgb(palette.blue400),
  gridStickyBackgroundColor: toRgba(palette.slate850, 0.98),
  gridStickyShadowColor: toRgba(palette.slate500, 0.35),
  gridHeaderStickyBackgroundColor: toRgba(palette.slate850, 0.98),
}

export const sugarTheme: DataGridStyleConfig = {
  inheritThemeFromDocument: true,
  defaultTokenVariant: "light",
  tokenVariants: {
    light: lightTokens,
    dark: darkTokens,
  },
}
