import { palette } from "./palette"
import { toRgb, toRgba, transparent } from "./colorUtils"
import type { DataGridStyleConfig, DataGridThemeTokens } from "./types"

const lightTokens: Partial<DataGridThemeTokens> = {
  gridFontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  gridFontSize: "0.86rem",
  gridTextColor: toRgb(palette.slate800),
  gridTextPrimary: toRgb(palette.slate900),
  gridTextMuted: toRgba(palette.slate700, 0.7),
  gridTextSoft: toRgba(palette.slate700, 0.55),
  gridBackgroundColor: toRgb(palette.white),
  gridViewportBackground: toRgb(palette.gray50),
  gridGlassBorder: toRgba(palette.gray300, 0.7),
  gridAccentStrong: toRgb(palette.blue600),
  gridHeaderRowBackgroundColor: toRgb(palette.gray100),
  gridHeaderCellBackgroundColor: toRgb(palette.gray100),
  gridHeaderCellHoverBackgroundColor: toRgb(palette.gray200),
  headerBackgroundColor: toRgb(palette.gray100),
  headerTextColor: toRgb(palette.zinc600),
  headerSystemTextColor: toRgb(palette.slate700),
  headerBorderColor: toRgba(palette.gray300, 0.8),
  headerPaddingX: "0.72rem",
  headerPaddingY: "0.42rem",
  headerHighlightBorderColor: toRgba(palette.blue500, 0.62),
  headerHighlightTextColor: toRgb(palette.blue600),
  headerSelectedTextColor: toRgb(palette.slate900),
  bodyRowBackgroundColor: toRgb(palette.white),
  bodyRowTextColor: toRgb(palette.slate800),
  bodyRowHoverBackgroundColor: toRgba(palette.blue400, 0.08),
  bodyRowSelectedBackgroundColor: toRgba(palette.blue400, 0.18),
  bodyRowSelectedTextColor: toRgb(palette.slate800),
  bodyCellPaddingX: "0.75rem",
  bodyCellPaddingY: "0.34rem",
  groupRowBackgroundColor: toRgba(palette.gray100, 0.9),
  groupRowTextColor: toRgb(palette.slate700),
  bodyCellBorderColor: toRgba(palette.gray300, 0.8),
  selectionCellBackgroundColor: toRgba(palette.blue200, 0.32),
  selectionCellTextColor: toRgb(palette.slate900),
  indexCellBackgroundColor: toRgb(palette.gray100),
  indexCellTextColor: toRgba(palette.slate700, 0.9),
  rowDividerColor: toRgba(palette.gray300, 0.7),
  rowDividerSize: "1px",
  columnDividerColor: toRgba(palette.gray300, 0.7),
  columnDividerSize: "1px",
  headerDividerColor: toRgba(palette.gray300, 0.72),
  headerDividerSize: "1px",
  summaryDividerSize: "1px",
  summaryDividerColor: toRgba(palette.gray300, 0.7),
  summaryRowBackgroundColor: toRgb(palette.gray100),
  summaryRowTextColor: toRgba(palette.slate800, 0.84),
  summaryLabelTextColor: toRgba(palette.slate700, 0.78),
  pinnedBackgroundColor: toRgb(palette.gray50),
  pinnedLeftBackgroundColor: toRgb(palette.gray50),
  pinnedRightBackgroundColor: toRgb(palette.gray50),
  pinnedShadow: `0 0 0 0 ${transparent()}`,
  pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.gray400, 0.28)}`,
  pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.gray400, 0.28)}`,
  pinnedLeftBorderColor: toRgba(palette.gray400, 0.48),
  pinnedLeftBorderWidth: "1px",
  pinnedRightBorderColor: toRgba(palette.gray400, 0.48),
  pinnedRightBorderWidth: "1px",
  gridHeroBackgroundStart: toRgba(palette.gray100, 0.92),
  gridHeroBackgroundEnd: toRgba(palette.white, 0.98),
  gridChipBackground: toRgba(palette.gray100, 0.86),
  gridControlsBackground: toRgba(palette.gray50, 0.94),
  gridControlsInputBackground: toRgba(palette.white, 0.98),
  gridControlsSurfaceBackground: toRgba(palette.white, 0.99),
  gridFilterPanelBorderColor: toRgba(palette.blue300, 0.38),
  gridFilterPanelBackground: toRgba(palette.white, 0.99),
  gridFilterIndicatorActiveColor: toRgb(palette.blue600),
  gridMetricsCardBackground: toRgba(palette.gray50, 0.96),
  gridFocusOutlineColor: toRgba(palette.blue500, 0.62),
  gridHeaderFilterOpenBackgroundColor: toRgb(palette.gray200),
  gridRowSelectedStickyBackgroundColor: toRgba(palette.blue200, 0.5),
  gridRowSelectedRangeBackgroundColor: toRgba(palette.blue200, 0.32),
  gridSelectionRangeBackgroundColor: toRgba(palette.blue400, 0.14),
  gridHeaderFilterHighlightColor: toRgba(palette.blue500, 0.56),
  gridFilterTriggerBorderColor: toRgba(palette.gray400, 0.46),
  gridFilterTriggerBackgroundColor: toRgba(palette.white, 0.96),
  gridFilterTriggerHoverBorderColor: toRgba(palette.blue500, 0.68),
  gridFilterTriggerHoverTextColor: toRgb(palette.blue600),
  gridFilterTriggerActiveBorderColor: toRgba(palette.blue500, 0.76),
  gridFilterTriggerActiveBackgroundColor: toRgba(palette.blue200, 0.62),
  gridFilterTriggerActiveTextColor: toRgb(palette.blue600),
  gridNumericTextColor: toRgb(palette.blue600),
  gridEditableHoverBackgroundColor: toRgba(palette.blue200, 0.24),
  gridSelectionActiveBorderColor: toRgba(palette.blue500, 0.7),
  gridSelectionCopiedBorderColor: toRgba(palette.blue300, 0.72),
  gridSelectionCopiedBackgroundColor: toRgba(palette.blue200, 0.28),
  gridSelectionHandleBackgroundColor: toRgb(palette.blue500),
  gridSelectionHandleBorderColor: toRgba(palette.blue500, 0.85),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.blue400, 0.12),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.blue400, 0.16),
  gridSelectionAnchorBackgroundColor: toRgba(palette.blue200, 0.34),
  gridEditorBackgroundColor: toRgb(palette.white),
  gridEditorBorderColor: toRgba(palette.gray400, 0.6),
  gridEditorFocusBorderColor: toRgba(palette.blue500, 0.8),
  gridEditorFocusRingColor: toRgba(palette.blue500, 0.2),
  gridEnumTriggerBorderColor: toRgba(palette.gray400, 0.52),
  gridEnumTriggerBackgroundColor: toRgb(palette.white),
  gridEnumTriggerTextColor: toRgb(palette.blue600),
  gridEnumTriggerHoverBorderColor: toRgba(palette.blue500, 0.72),
  gridEnumTriggerHoverBackgroundColor: toRgba(palette.blue200, 0.42),
  gridResizeHandleHoverColor: toRgba(palette.blue500, 0.8),
  gridSortIndicatorColor: toRgb(palette.blue600),
  gridSortPriorityBorderColor: toRgba(palette.blue400, 0.4),
  gridCheckboxAccentColor: toRgb(palette.blue600),
  gridGroupRowBorderColor: toRgba(palette.blue300, 0.22),
  gridGroupStartGradientStart: toRgba(palette.blue200, 0.14),
  gridGroupStartGradientEnd: toRgba(palette.gray50, 0.98),
  gridGroupBadgeTextColor: toRgba(palette.slate700, 0.82),
  gridSelectionOverlayBorderColor: toRgba(palette.blue500, 0.72),
  gridSelectionOverlayBackgroundColor: toRgba(palette.blue200, 0.18),
  gridSelectionOverlayFillBorderColor: toRgba(palette.blue500, 0.68),
  gridSelectionOverlayFillBackgroundColor: toRgba(palette.blue200, 0.16),
  gridSelectionOverlayMoveBorderColor: toRgba(palette.blue400, 0.72),
  gridSelectionOverlayMoveBackgroundColor: toRgba(palette.blue200, 0.14),
  gridStickyBackgroundColor: toRgba(palette.gray100, 0.98),
  gridStickyShadowColor: toRgba(palette.gray400, 0.28),
  gridStickyRangeBackgroundColor: toRgba(palette.blue200, 0.38),
  gridStickyRangeBorderColor: toRgba(palette.blue400, 0.48),
  gridStickyAnchorBackgroundColor: toRgba(palette.blue200, 0.52),
  gridStickyAnchorBorderColor: toRgba(palette.blue400, 0.68),
  gridStickyActiveBorderColor: toRgba(palette.blue500, 0.82),
  gridHeaderStickyBackgroundColor: toRgba(palette.gray100, 0.98),
  gridMoveHandleHoverBackgroundColor: toRgba(palette.blue200, 0.36),
  gridHintBorderColor: toRgba(palette.gray300, 0.72),
  gridHintBackgroundColor: toRgba(palette.gray50, 0.96),
  gridCopyMenuBorderColor: toRgba(palette.blue300, 0.38),
  gridCopyMenuBackgroundColor: toRgba(palette.white, 0.99),
  gridCopyMenuShadowColor: toRgba(palette.gray400, 0.18),
  gridCopyMenuItemHoverBorderColor: toRgba(palette.blue400, 0.36),
  gridCopyMenuItemHoverBackgroundColor: toRgba(palette.blue200, 0.36),
  gridColumnMenuBorderColor: toRgba(palette.gray300, 0.82),
  gridColumnMenuBackgroundColor: toRgba(palette.white, 0.99),
  gridColumnMenuShadowColor: toRgba(palette.gray400, 0.16),
  gridColumnMenuItemHoverBackgroundColor: toRgba(palette.blue300, 0.18),
  gridColumnMenuMutedTextColor: toRgba(palette.slate700, 0.72),
  gridColumnMenuFocusRingColor: toRgba(palette.blue500, 0.22),
  gridColumnMenuSearchBorderColor: toRgba(palette.gray400, 0.72),
  gridColumnMenuSearchBackgroundColor: toRgba(palette.gray50, 0.98),
}

const darkTokens: Partial<DataGridThemeTokens> = {
  gridFontFamily: "'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  gridFontSize: "0.86rem",
  gridTextColor: toRgb(palette.gray100),
  gridTextPrimary: toRgb(palette.gray50),
  gridTextMuted: toRgba(palette.gray200, 0.75),
  gridTextSoft: toRgba(palette.gray200, 0.55),
  gridBackgroundColor: toRgb(palette.midnight950),
  gridViewportBackground: toRgba(palette.slate900, 0.96),
  gridGlassBorder: toRgba(palette.slate600, 0.5),
  gridAccentStrong: toRgb(palette.blue400),
  gridHeaderRowBackgroundColor: toRgba(palette.slate850, 0.98),
  gridHeaderCellBackgroundColor: toRgba(palette.slate850, 0.98),
  gridHeaderCellHoverBackgroundColor: toRgba(palette.slate700, 0.9),
  headerBackgroundColor: toRgba(palette.slate850, 0.98),
  headerTextColor: toRgba(palette.gray200, 0.9),
  headerSystemTextColor: toRgba(palette.gray200, 0.82),
  headerBorderColor: toRgba(palette.slate600, 0.6),
  headerPaddingX: "0.72rem",
  headerPaddingY: "0.42rem",
  headerHighlightBorderColor: toRgba(palette.blue300, 0.72),
  headerHighlightTextColor: toRgba(palette.blue200, 0.95),
  headerSelectedTextColor: toRgb(palette.gray50),
  bodyRowBackgroundColor: toRgba(palette.slate900, 0.96),
  bodyRowTextColor: toRgb(palette.gray100),
  bodyRowHoverBackgroundColor: toRgba(palette.blue400, 0.14),
  bodyRowSelectedBackgroundColor: toRgba(palette.blue400, 0.24),
  bodyRowSelectedTextColor: toRgb(palette.gray100),
  bodyCellPaddingX: "0.75rem",
  bodyCellPaddingY: "0.34rem",
  groupRowBackgroundColor: toRgba(palette.slate800, 0.72),
  groupRowTextColor: toRgba(palette.gray200, 0.86),
  bodyCellBorderColor: toRgba(palette.slate600, 0.6),
  selectionCellBackgroundColor: toRgba(palette.blue400, 0.2),
  selectionCellTextColor: toRgb(palette.gray50),
  indexCellBackgroundColor: toRgba(palette.slate850, 0.98),
  indexCellTextColor: toRgba(palette.gray200, 0.86),
  rowDividerColor: toRgba(palette.slate600, 0.55),
  rowDividerSize: "1px",
  columnDividerColor: toRgba(palette.slate600, 0.55),
  columnDividerSize: "1px",
  headerDividerColor: toRgba(palette.slate600, 0.64),
  headerDividerSize: "1px",
  summaryDividerSize: "1px",
  summaryDividerColor: toRgba(palette.slate600, 0.55),
  summaryRowBackgroundColor: toRgba(palette.slate850, 0.98),
  summaryRowTextColor: toRgba(palette.gray200, 0.84),
  summaryLabelTextColor: toRgba(palette.gray300, 0.78),
  pinnedBackgroundColor: toRgba(palette.slate850, 0.98),
  pinnedLeftBackgroundColor: toRgba(palette.slate850, 0.98),
  pinnedRightBackgroundColor: toRgba(palette.slate850, 0.98),
  pinnedShadow: `0 0 0 0 ${transparent()}`,
  pinnedLeftShadow: `inset -1px 0 0 ${toRgba(palette.slate500, 0.38)}`,
  pinnedRightShadow: `inset 1px 0 0 ${toRgba(palette.slate500, 0.38)}`,
  pinnedLeftBorderColor: toRgba(palette.slate500, 0.56),
  pinnedLeftBorderWidth: "1px",
  pinnedRightBorderColor: toRgba(palette.slate500, 0.56),
  pinnedRightBorderWidth: "1px",
  gridHeroBackgroundStart: toRgba(palette.midnight950, 0.94),
  gridHeroBackgroundEnd: toRgba(palette.slate850, 0.92),
  gridChipBackground: toRgba(palette.gray200, 0.08),
  gridControlsBackground: toRgba(palette.midnight950, 0.9),
  gridControlsInputBackground: toRgba(palette.slate800, 0.58),
  gridControlsSurfaceBackground: toRgba(palette.slate850, 0.98),
  gridFilterPanelBorderColor: toRgba(palette.blue300, 0.34),
  gridFilterPanelBackground: toRgba(palette.slate850, 0.97),
  gridFilterIndicatorActiveColor: toRgba(palette.blue300, 0.95),
  gridMetricsCardBackground: toRgba(palette.midnight950, 0.9),
  gridFocusOutlineColor: toRgba(palette.blue400, 0.62),
  gridHeaderFilterOpenBackgroundColor: toRgba(palette.slate700, 0.92),
  gridRowSelectedStickyBackgroundColor: toRgba(palette.blue400, 0.28),
  gridRowSelectedRangeBackgroundColor: toRgba(palette.blue400, 0.2),
  gridSelectionRangeBackgroundColor: toRgba(palette.blue400, 0.18),
  gridHeaderFilterHighlightColor: toRgba(palette.blue400, 0.58),
  gridFilterTriggerBorderColor: toRgba(palette.slate500, 0.48),
  gridFilterTriggerBackgroundColor: toRgba(palette.slate800, 0.94),
  gridFilterTriggerHoverBorderColor: toRgba(palette.blue300, 0.78),
  gridFilterTriggerHoverTextColor: toRgba(palette.blue200, 0.96),
  gridFilterTriggerActiveBorderColor: toRgba(palette.blue300, 0.84),
  gridFilterTriggerActiveBackgroundColor: toRgba(palette.blue400, 0.24),
  gridFilterTriggerActiveTextColor: toRgba(palette.blue200, 1),
  gridNumericTextColor: toRgb(palette.blue200),
  gridEditableHoverBackgroundColor: toRgba(palette.slate700, 0.56),
  gridSelectionActiveBorderColor: toRgba(palette.blue300, 0.85),
  gridSelectionCopiedBorderColor: toRgba(palette.blue300, 0.84),
  gridSelectionCopiedBackgroundColor: toRgba(palette.blue400, 0.12),
  gridSelectionHandleBackgroundColor: toRgb(palette.blue400),
  gridSelectionHandleBorderColor: toRgba(palette.blue300, 0.9),
  gridSelectionFillPreviewBackgroundColor: toRgba(palette.blue400, 0.16),
  gridSelectionMovePreviewBackgroundColor: toRgba(palette.blue400, 0.2),
  gridSelectionAnchorBackgroundColor: toRgba(palette.blue400, 0.24),
  gridEditorBackgroundColor: toRgba(palette.slate800, 0.96),
  gridEditorBorderColor: toRgba(palette.slate500, 0.6),
  gridEditorFocusBorderColor: toRgba(palette.blue300, 0.85),
  gridEditorFocusRingColor: toRgba(palette.blue400, 0.25),
  gridEnumTriggerBorderColor: toRgba(palette.slate500, 0.48),
  gridEnumTriggerBackgroundColor: toRgba(palette.slate800, 0.96),
  gridEnumTriggerTextColor: toRgba(palette.blue200, 0.95),
  gridEnumTriggerHoverBorderColor: toRgba(palette.blue300, 0.8),
  gridEnumTriggerHoverBackgroundColor: toRgba(palette.slate700, 0.88),
  gridResizeHandleHoverColor: toRgba(palette.blue300, 0.85),
  gridSortIndicatorColor: toRgba(palette.blue300, 0.95),
  gridSortPriorityBorderColor: toRgba(palette.blue300, 0.45),
  gridCheckboxAccentColor: toRgb(palette.blue400),
  gridGroupRowBorderColor: toRgba(palette.blue300, 0.28),
  gridGroupStartGradientStart: toRgba(palette.blue400, 0.12),
  gridGroupStartGradientEnd: toRgba(palette.slate900, 0.9),
  gridGroupBadgeTextColor: toRgba(palette.gray200, 0.8),
  gridSelectionOverlayBorderColor: toRgba(palette.blue400, 0.88),
  gridSelectionOverlayBackgroundColor: toRgba(palette.blue400, 0.1),
  gridSelectionOverlayFillBorderColor: toRgba(palette.blue300, 0.88),
  gridSelectionOverlayFillBackgroundColor: toRgba(palette.blue400, 0.08),
  gridSelectionOverlayMoveBorderColor: toRgba(palette.blue300, 0.88),
  gridSelectionOverlayMoveBackgroundColor: toRgba(palette.blue400, 0.08),
  gridStickyBackgroundColor: toRgba(palette.slate850, 0.98),
  gridStickyShadowColor: toRgba(palette.slate500, 0.35),
  gridStickyRangeBackgroundColor: toRgba(palette.blue400, 0.24),
  gridStickyRangeBorderColor: toRgba(palette.blue300, 0.54),
  gridStickyAnchorBackgroundColor: toRgba(palette.blue400, 0.3),
  gridStickyAnchorBorderColor: toRgba(palette.blue200, 0.78),
  gridStickyActiveBorderColor: toRgba(palette.blue200, 0.95),
  gridHeaderStickyBackgroundColor: toRgba(palette.slate850, 0.98),
  gridMoveHandleHoverBackgroundColor: toRgba(palette.blue300, 0.2),
  gridHintBorderColor: toRgba(palette.slate600, 0.38),
  gridHintBackgroundColor: toRgba(palette.midnight950, 0.9),
  gridCopyMenuBorderColor: toRgba(palette.blue300, 0.34),
  gridCopyMenuBackgroundColor: toRgba(palette.slate850, 0.98),
  gridCopyMenuShadowColor: toRgba(palette.black, 0.34),
  gridCopyMenuItemHoverBorderColor: toRgba(palette.blue300, 0.4),
  gridCopyMenuItemHoverBackgroundColor: toRgba(palette.slate700, 0.78),
  gridColumnMenuBorderColor: toRgba(palette.slate600, 0.66),
  gridColumnMenuBackgroundColor: toRgba(palette.midnight950, 0.985),
  gridColumnMenuShadowColor: toRgba(palette.black, 0.34),
  gridColumnMenuItemHoverBackgroundColor: toRgba(palette.blue400, 0.2),
  gridColumnMenuMutedTextColor: toRgba(palette.gray300, 0.72),
  gridColumnMenuFocusRingColor: toRgba(palette.blue400, 0.26),
  gridColumnMenuSearchBorderColor: toRgba(palette.slate500, 0.72),
  gridColumnMenuSearchBackgroundColor: toRgba(palette.slate850, 0.98),
}

export const sugarTheme: DataGridStyleConfig = {
  inheritThemeFromDocument: true,
  defaultTokenVariant: "light",
  tokenVariants: {
    light: lightTokens,
    dark: darkTokens,
  },
}
